"""LK auth router — one-time token exchange for JWT."""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from shared.models import User

from ..database import get_async_session
from ..dependencies import create_lk_jwt, get_raw_redis
from ..schemas.lk import TokenExchangeRequest, TokenExchangeResponse

router = APIRouter(prefix="/lk/auth", tags=["lk-auth"])

LK_TOKEN_PREFIX = "lk_token:"  # noqa: S105 — Redis key prefix, not a password


@router.post("/token", response_model=TokenExchangeResponse)
async def exchange_token(
    body: TokenExchangeRequest,
    redis=Depends(get_raw_redis),
    db: AsyncSession = Depends(get_async_session),
) -> TokenExchangeResponse:
    """Exchange a one-time token for a JWT.

    The token was generated by Telegram bot and stored in Redis
    as `lk_token:{token} → user_id` with a 5-minute TTL.
    """
    redis_key = f"{LK_TOKEN_PREFIX}{body.token}"

    # Get and delete atomically (one-time use)
    user_id_str = await redis.getdel(redis_key)
    if user_id_str is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired token",
        )

    user_id = int(user_id_str)

    # Verify user exists
    result = await db.execute(select(User).where(User.id == user_id))
    user = result.scalar_one_or_none()
    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="User not found",
        )

    access_token = create_lk_jwt(user.id)
    return TokenExchangeResponse(access_token=access_token)
