"""Schemas for LangGraph orchestrator."""

from enum import Enum

from pydantic import BaseModel, Field


class EntryPoint(str, Enum):
    """Available entry points for projects."""

    TELEGRAM = "telegram"
    FRONTEND = "frontend"
    API = "api"


class ProjectSpec(BaseModel):
    """Project specification generated by Brainstorm agent.

    This schema defines what Brainstorm produces after gathering requirements.
    It contains all information needed to create and deploy a project.
    """

    name: str = Field(..., description="Project name in snake_case")
    description: str = Field(..., description="Brief project description")
    modules: list[str] = Field(
        ...,
        description="Modules to generate: backend, telegram_worker, notifications_worker",
    )
    entry_points: list[EntryPoint] = Field(..., description="Entry points: telegram, frontend, api")

    # Hardcoded defaults for MVP (will be calculated later)
    estimated_ram_mb: int = Field(default=512, description="Estimated RAM needed in MB")
    estimated_disk_mb: int = Field(default=2048, description="Estimated disk space in MB")
