"""A Python service image installs exactly its lock, and the lock satisfies its pyproject.

The comparison runs over fixtures shaped the way the probe prints an image, so every
kind of drift (an added, a removed, a re-versioned package) is shown red without a
Docker build. The tree-level tests read the real Dockerfiles, locks and Makefile.
"""

import json
from pathlib import Path
import re
import subprocess
import sys

import pytest
import yaml

from scripts import service_image_locks as locks

ROOT = Path(__file__).resolve().parents[2]
BROKER = ROOT / "services" / "worker-broker"
LOCKED_SERVICES = sorted(path.parent for path in ROOT.glob("services/*/requirements.lock"))
ENVIRONMENT = {
    "implementation_name": "cpython",
    "implementation_version": "3.12.13",
    "os_name": "posix",
    "platform_machine": "x86_64",
    "platform_python_implementation": "CPython",
    "platform_release": "6.8.0",
    "platform_system": "Linux",
    "platform_version": "#1 SMP",
    "python_full_version": "3.12.13",
    "python_version": "3.12",
    "sys_platform": "linux",
}
PYPROJECT = """
[project]
name = "demo-service"
version = "0.1.0"
dependencies = ["httpx>=0.27.0", "pyjwt[crypto]>=2.13.0"]
"""
LOCK = """# This file was autogenerated by uv via the following command:
#    uv pip compile services/demo/pyproject.toml -o services/demo/requirements.lock
cryptography==46.0.3
    # via pyjwt
httpx==0.28.1
    # via demo-service (services/demo/pyproject.toml)
pyjwt==2.13.0
    # via demo-service (services/demo/pyproject.toml)
"""


def _dist(name, version, *requires):
    return {"name": name, "version": version, "requires": list(requires)}


def _image(*extra, drop=(), versions=None):
    """A probe output of an image that installed LOCK, then changed as asked."""
    versions = versions or {}
    dists = [
        _dist("pip", "25.2"),
        _dist("demo-service", "0.1.0", "httpx>=0.27.0", "PyJWT[crypto]>=2.13.0"),
        _dist("cryptography", "46.0.3"),
        _dist("httpx", "0.28.1"),
        _dist("PyJWT", "2.13.0", 'cryptography>=3.4.0; extra == "crypto"'),
        *extra,
    ]
    dists = [
        {**dist, "version": versions.get(dist["name"], dist["version"])}
        for dist in dists
        if dist["name"] not in drop
    ]
    return json.dumps({"distributions": dists, "environment": ENVIRONMENT})


def test_an_image_that_installed_exactly_its_lock_passes():
    """pip and the service's own package are ignored; everything else is the lock."""
    assert locks.check_image("demo", LOCK, PYPROJECT, _image()) == []


def test_an_added_package_fails_naming_the_image_and_the_package():
    problems = locks.check_image("demo", LOCK, PYPROJECT, _image(_dist("requests", "2.32.3")))

    assert problems == ["demo: requests 2.32.3 is installed, but requirements.lock does not pin it"]


def test_a_removed_package_fails_naming_the_locked_version():
    problems = locks.check_image("demo", LOCK, PYPROJECT, _image(drop=("httpx",)))

    assert "demo: requirements.lock pins httpx 0.28.1, but it is not installed" in problems


def test_a_re_versioned_package_fails_naming_both_versions():
    problems = locks.check_image("demo", LOCK, PYPROJECT, _image(versions={"httpx": "0.27.2"}))

    assert problems == ["demo: httpx is installed at 0.27.2, but requirements.lock pins 0.28.1"]


def test_only_the_installer_tooling_and_the_own_package_are_ignored():
    tooling = (_dist("setuptools", "80.0"), _dist("wheel", "0.45"))
    assert locks.check_image("demo", LOCK, PYPROJECT, _image(*tooling)) == []

    problems = locks.check_image("demo", LOCK, PYPROJECT, _image(_dist("other-service", "0.1")))
    assert problems == [
        "demo: other-service 0.1 is installed, but requirements.lock does not pin it"
    ]


def test_one_distribution_installed_at_two_versions_is_drift():
    problems = locks.check_image("demo", LOCK, PYPROJECT, _image(_dist("httpx", "0.27.2")))

    assert problems == ["demo: httpx is installed twice, at 0.28.1 and 0.27.2"]


def test_names_compare_canonically_and_versions_numerically():
    pins = {"pyjwt": "2.13.0", "typing-extensions": "4.16"}
    installed, _ = locks.installed_distributions(
        "demo", [_dist("PyJWT", "2.13"), _dist("typing_extensions", "4.16.0")]
    )

    assert locks.drift("demo", pins, installed, "demo-service") == []


def test_a_lock_behind_a_raised_pyproject_minimum_is_stale():
    raised = PYPROJECT.replace("httpx>=0.27.0", "httpx>=0.29.0")

    assert locks.check_lock_against_pyproject("demo", LOCK, raised, ENVIRONMENT) == [
        "demo: pyproject.toml requires httpx>=0.29.0, but requirements.lock pins httpx 0.28.1"
    ]
    assert locks.check_image("demo", LOCK, raised, _image()) == [
        "demo: pyproject.toml requires httpx>=0.29.0, but requirements.lock pins httpx 0.28.1"
    ]


def test_a_dependency_added_to_pyproject_but_not_the_lock_is_stale():
    added = PYPROJECT.replace('"httpx>=0.27.0"', '"httpx>=0.27.0", "aiohttp>=3.14.3"')

    assert locks.check_lock_against_pyproject("demo", LOCK, added, ENVIRONMENT) == [
        "demo: pyproject.toml requires aiohttp>=3.14.3, which requirements.lock does not pin"
    ]


def test_the_image_walk_follows_extras_the_bare_lock_cannot_see():
    """pyjwt[crypto] needs cryptography: only the image's metadata says so."""
    lock = LOCK.replace("cryptography==46.0.3\n", "")
    image = _image(drop=("cryptography",))

    assert locks.check_lock_against_pyproject("demo", lock, PYPROJECT, ENVIRONMENT) == []
    assert locks.check_image("demo", lock, PYPROJECT, image) == [
        'demo: pyjwt 2.13.0 requires cryptography>=3.4.0; extra == "crypto", '
        "which requirements.lock does not pin"
    ]


def test_a_requirement_whose_marker_does_not_hold_is_not_required():
    windows_only = PYPROJECT.replace(
        '"httpx>=0.27.0"', '"httpx>=0.27.0", "pywin32>=306; sys_platform == \'win32\'"'
    )

    assert locks.check_image("demo", LOCK, windows_only, _image()) == []


def test_a_lock_pin_whose_marker_does_not_hold_is_not_expected_installed():
    lock = LOCK + "colorama==0.4.6 ; sys_platform == 'win32'\n"

    assert locks.parse_lock(lock, ENVIRONMENT) == {
        "cryptography": "46.0.3",
        "httpx": "0.28.1",
        "pyjwt": "2.13.0",
    }


@pytest.mark.parametrize("line", ["httpx>=0.27", "httpx", "-e ."])
def test_a_lock_line_that_is_not_an_exact_pin_refuses_the_lock(line):
    with pytest.raises(ValueError, match="line 2"):
        locks.parse_lock(f"# header\n{line}\n", ENVIRONMENT)


def test_the_probe_runs_on_a_bare_interpreter_and_describes_it():
    """Standard library only: it runs in images that may not carry packaging."""
    output = subprocess.run(
        [sys.executable, "-I", "-S", "-c", locks.PROBE],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    probe = json.loads(output)

    assert probe["environment"]["python_version"] == f"{sys.version_info[0]}.{sys.version_info[1]}"
    assert set(probe["environment"]) == set(ENVIRONMENT)
    assert isinstance(probe["distributions"], list)


def test_the_probe_of_this_interpreter_reads_its_own_distributions():
    output = subprocess.run(
        [sys.executable, "-c", locks.PROBE], capture_output=True, text=True, check=True
    ).stdout
    names = {entry["name"].lower() for entry in json.loads(output)["distributions"]}

    assert "packaging" in names


# --- the tree ---------------------------------------------------------------


@pytest.mark.parametrize("service", LOCKED_SERVICES, ids=lambda path: path.name)
def test_every_lock_satisfies_its_pyproject(service):
    """The cheap freshness check: a pyproject edit without `make lock-deps` fails here."""
    problems = locks.check_lock_against_pyproject(
        service.name,
        (service / "requirements.lock").read_text(),
        (service / "pyproject.toml").read_text(),
        ENVIRONMENT,
    )

    assert problems == [], "run `make lock-deps`:\n" + "\n".join(problems)


@pytest.mark.parametrize("service", LOCKED_SERVICES, ids=lambda path: path.name)
def test_make_lock_deps_generates_every_lock(service):
    relative = service.relative_to(ROOT)
    command = f"uv pip compile {relative}/pyproject.toml -o {relative}/requirements.lock"
    recipe = (ROOT / "Makefile").read_text().split("\nlock-deps:", 1)[1].split("\n\n", 1)[0]

    assert command in recipe


def _instructions(dockerfile: Path) -> list[str]:
    """The Dockerfile's instructions, continuation lines joined, comments dropped."""
    joined = re.sub(r"\\\n", " ", dockerfile.read_text())
    lines = (line.strip() for line in joined.splitlines())
    return [line for line in lines if line and not line.startswith("#")]


@pytest.mark.parametrize("service", LOCKED_SERVICES, ids=lambda path: path.name)
def test_the_lock_is_installed_with_a_cache_before_any_source(service):
    """A shared/ or src/ edit must reuse the dependency layer, and the layer is the lock."""
    instructions = _instructions(service / "Dockerfile")
    lock_copy = next(
        index
        for index, line in enumerate(instructions)
        if line.startswith("COPY") and f"{service.relative_to(ROOT)}/requirements.lock" in line
    )
    install = next(
        index
        for index, line in enumerate(instructions)
        if index > lock_copy and re.search(r"pip install .*-r \S*requirements\.lock", line)
    )
    sources = [
        index
        for index, line in enumerate(instructions)
        if re.match(rf"COPY\s+(--\S+\s+)*(shared|{service.relative_to(ROOT)}/src)\b", line)
    ]

    assert "--mount=type=cache,target=/root/.cache/pip" in instructions[install]
    assert sources and install < min(sources)
    for line in instructions:
        for command in re.findall(r"pip install[^&;]*", line):
            assert "requirements.lock" in command or "--no-deps" in command, (
                f"{command!r} would resolve dependencies outside the lock"
            )


def test_the_ansible_collections_are_pinned_and_installed_before_the_source():
    service = ROOT / "services" / "infra-service"
    requirements = yaml.safe_load((service / "ansible" / "requirements.yml").read_text())
    for collection in requirements["collections"]:
        assert re.fullmatch(r"\d+\.\d+\.\d+", collection["version"]), collection

    instructions = _instructions(service / "Dockerfile")
    galaxy = next(i for i, line in enumerate(instructions) if "ansible-galaxy" in line)
    source = next(i for i, line in enumerate(instructions) if "infra-service/src" in line)
    assert galaxy < source


def test_the_worker_broker_fixture_lock_is_the_real_one():
    """The real broker lock read back as an image installs cleanly: the fixture shape holds."""
    lock = (BROKER / "requirements.lock").read_text()
    pins = locks.parse_lock(lock, ENVIRONMENT)
    image = json.dumps(
        {
            "distributions": [_dist("pip", "25.2")]
            + [_dist(name, version) for name, version in pins.items()],
            "environment": ENVIRONMENT,
        }
    )

    assert (
        locks.check_image("worker-broker", lock, (BROKER / "pyproject.toml").read_text(), image)
        == []
    )
