#!/usr/bin/env python3
"""Preparer Script.

Prepares a project repository with service-template via copier.
Runs inside a lightweight Docker container.

Environment Variables:
    REPO_URL: Git repository URL (with auth token embedded)
    PROJECT_NAME: Name of the project (snake_case)
    MODULES: Comma-separated list of modules (e.g., "backend,tg_bot")
    TASK_MD: Content for TASK.md file
    AGENTS_MD: Content for AGENTS.md file (optional)
    SERVICE_TEMPLATE_REF: Git ref for service-template (default: main)
"""

import json
import os
from pathlib import Path
import subprocess
import sys


def log(message: str, **kwargs) -> None:
    """Log a structured message to stdout."""
    data = {"message": message, **kwargs}
    print(json.dumps(data), flush=True)


def run_command(cmd: list[str], check: bool = True, **kwargs) -> subprocess.CompletedProcess:
    """Run a command and log it."""
    log("running_command", command=" ".join(cmd))
    result = subprocess.run(cmd, capture_output=True, text=True, **kwargs)
    if result.returncode != 0 and check:
        log(
            "command_failed",
            command=" ".join(cmd),
            exit_code=result.returncode,
            stdout=result.stdout,
            stderr=result.stderr,
        )
        raise subprocess.CalledProcessError(result.returncode, cmd, result.stdout, result.stderr)
    return result


def main() -> int:
    """Main entry point."""
    # Read environment variables
    repo_url = os.environ.get("REPO_URL")
    project_name = os.environ.get("PROJECT_NAME")
    modules = os.environ.get("MODULES", "backend")
    task_md = os.environ.get("TASK_MD", "")
    agents_md = os.environ.get("AGENTS_MD", "")
    service_template_ref = os.environ.get("SERVICE_TEMPLATE_REF", "main")

    # Validate required env vars
    if not repo_url:
        log("error", message="REPO_URL environment variable is required")
        return 1
    if not project_name:
        log("error", message="PROJECT_NAME environment variable is required")
        return 1

    log(
        "preparer_starting",
        project_name=project_name,
        modules=modules,
        service_template_ref=service_template_ref,
    )

    workspace = Path("/workspace")
    workspace.mkdir(exist_ok=True)
    os.chdir(workspace)

    try:
        # Clone the repository
        log("cloning_repository", repo_url=repo_url.split("@")[0] + "@***")  # Hide token in logs
        run_command(["git", "clone", repo_url, "."])

        # Run copier to generate project structure
        template_url = "gh:vladmesh/service-template"
        if service_template_ref != "main":
            template_url = f"{template_url}@{service_template_ref}"

        log("running_copier", template=template_url, modules=modules, vcs_ref=service_template_ref)
        run_command(
            [
                "copier",
                "copy",
                template_url,
                ".",
                "--vcs-ref",
                service_template_ref,  # Force specific ref, avoid cache
                "--data",
                f"project_name={project_name}",
                "--data",
                f"modules={modules}",
                "--trust",
                "--defaults",
                "--overwrite",
            ]
        )

        # Write TASK.md if provided
        if task_md:
            log("writing_task_md")
            Path("TASK.md").write_text(task_md)

        # Write AGENTS.md if provided
        if agents_md:
            log("writing_agents_md")
            Path("AGENTS.md").write_text(agents_md)

        # Git add, commit, and push
        log("committing_changes")
        run_command(["git", "add", "."])

        # Check if there are changes to commit
        status_result = run_command(["git", "status", "--porcelain"], check=False)
        if not status_result.stdout.strip():
            log("no_changes_to_commit")
            # Still get the current HEAD for response
            head_result = run_command(["git", "rev-parse", "HEAD"])
            commit_sha = head_result.stdout.strip()
        else:
            run_command(
                [
                    "git",
                    "commit",
                    "--no-verify",  # Skip pre-commit hooks (make not available in container)
                    "-m",
                    f"Initialize project structure via service-template\n\n"
                    f"Modules: {modules}\n"
                    f"Generated by Codegen Orchestrator Preparer",
                ]
            )

            log("pushing_changes")
            run_command(["git", "push", "--no-verify"])  # Skip pre-push hooks

            # Get commit SHA
            head_result = run_command(["git", "rev-parse", "HEAD"])
            commit_sha = head_result.stdout.strip()

        # Output result in expected format
        log("preparer_complete", commit_sha=commit_sha)
        print(f"COMMIT_SHA={commit_sha}")
        return 0

    except subprocess.CalledProcessError as e:
        log(
            "preparer_failed",
            error=str(e),
            stdout=e.stdout if hasattr(e, "stdout") else None,
            stderr=e.stderr if hasattr(e, "stderr") else None,
        )
        return 1
    except Exception as e:
        log("preparer_failed", error=str(e), error_type=type(e).__name__)
        return 1


if __name__ == "__main__":
    sys.exit(main())
