#!/usr/bin/env python3
"""Generate docs/ROADMAP.md from Stories API.

Usage:
    python scripts/generate_roadmap.py [--api-url URL] [--output PATH]
"""

import argparse
from datetime import UTC, datetime
from pathlib import Path

import httpx

DEFAULT_API_URL = "http://localhost:8000"
DEFAULT_OUTPUT = "docs/ROADMAP.md"
DONE_STATUSES = {"done", "completed"}


async def fetch_roadmap_data(api_url: str, project_id: str | None) -> tuple[list[dict], list[dict]]:
    """Fetch stories (with tasks) and unlinked tasks from the API."""
    async with httpx.AsyncClient(base_url=api_url, timeout=10) as client:
        # Fetch all stories
        params: dict = {}
        if project_id:
            params["project_id"] = project_id
        stories_resp = await client.get("/api/stories/", params=params)
        stories_resp.raise_for_status()
        stories = stories_resp.json()

        # Fetch tasks for each story
        for story in stories:
            tasks_resp = await client.get("/api/tasks/", params={"story_id": story["id"]})
            tasks_resp.raise_for_status()
            story["tasks"] = tasks_resp.json()

        # Unlinked: backlog tasks without a story
        backlog_params: dict = {"status": "backlog"}
        if project_id:
            backlog_params["project_id"] = project_id
        backlog_resp = await client.get("/api/tasks/", params=backlog_params)
        backlog_resp.raise_for_status()
        all_backlog = backlog_resp.json()
        unlinked = [t for t in all_backlog if not t.get("story_id")]

    return stories, unlinked


def format_roadmap(stories: list[dict], unlinked_tasks: list[dict]) -> str:
    """Format stories and tasks into ROADMAP markdown."""
    today = datetime.now(UTC).strftime("%Y-%m-%d")
    lines = [
        "# Roadmap",
        "",
        "> [!WARNING]",
        "> This file is auto-generated by `make sync`."
        " Do not edit manually — changes will be overwritten.",
        "",
        f"> **Updated**: {today}",
        "",
    ]

    product = [s for s in stories if s.get("type", "product") == "product"]
    technical = [s for s in stories if s.get("type") == "technical"]

    if product:
        lines.append("# Product Roadmap")
        lines.append("")
        _render_stories(lines, product)

    if technical:
        lines.append("# Technical Initiatives")
        lines.append("")
        _render_stories(lines, technical)

    if unlinked_tasks:
        lines.append("## Unlinked Tasks")
        lines.append("")
        for task in unlinked_tasks:
            checkbox = "x" if task["status"] in DONE_STATUSES else " "
            lines.append(f"- [{checkbox}] {task['title']}")
        lines.append("")

    return "\n".join(lines)


def _render_stories(lines: list[str], stories: list[dict]) -> None:
    """Render a list of stories with their tasks."""
    for story in stories:
        title = story["title"]
        status = story.get("status", "active")
        description = story.get("description")
        tasks = story.get("tasks", [])

        if status == "completed":
            lines.append(f"## {title} — COMPLETE")
            lines.append("")
            if description:
                lines.append(f"_{description}_")
                lines.append("")
        else:
            lines.append(f"## {title}")
            lines.append("")
            if description:
                lines.append(description)
                lines.append("")

            for task in tasks:
                checkbox = "x" if task["status"] in DONE_STATUSES else " "
                lines.append(f"- [{checkbox}] {task['title']}")

            if tasks:
                lines.append("")


async def main(api_url: str, output: str, project_id: str) -> None:
    stories, unlinked = await fetch_roadmap_data(api_url, project_id)
    content = format_roadmap(stories, unlinked)

    Path(output).write_text(content)
    print(f"Generated {output} — {len(stories)} stories")


if __name__ == "__main__":
    import asyncio

    parser = argparse.ArgumentParser(description="Generate ROADMAP.md from API")
    parser.add_argument("--api-url", default=DEFAULT_API_URL)
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--project-id", default=None, help="Project UUID (resolves first project if omitted)"
    )
    args = parser.parse_args()

    asyncio.run(main(args.api_url, args.output, args.project_id))
