#!/usr/bin/env bash
# Record what the deploy-infra prerequisite suite does against a live stack.
#
# CI cannot run tests/live/test_deploy_infra.py: it needs a managed server, a
# reachable VPS and the allocation API. This script executes the whole suite and
# writes a machine-generated artifact to docs/e2e_results/, so the run is
# reproducible by anyone with a stack instead of being retold second-hand.
#
# The artifact records the SHA under test, per-test results parsed from the
# JUnit report, and the allocation state before and after, so a test that
# silently skipped or an allocation left behind is visible in it.
#
# Usage, from a checkout of the SHA under test, with `make up` running:
#
#   INTERNAL_API_KEY=... ORCHESTRATOR_ROOT=/path/to/the/stack/checkout \
#     ./scripts/live_deploy_infra_evidence.sh
#
# ORCHESTRATOR_ROOT must point at the checkout the stack was started from, so
# `docker compose exec` reaches those containers.
set -euo pipefail

: "${INTERNAL_API_KEY:?INTERNAL_API_KEY is required — the suite calls auth-gated endpoints}"
: "${ORCHESTRATOR_ROOT:?ORCHESTRATOR_ROOT must point at the checkout the stack runs from}"
API_URL="${API_URL:-http://localhost:8000}"

REPO="$(cd "$(dirname "$0")/.." && pwd)"
SHA="$(git -C "$REPO" rev-parse HEAD)"
SHORT_SHA="$(git -C "$REPO" rev-parse --short HEAD)"
# Content hash of the live tests that ran. Committing this artifact necessarily
# moves HEAD past the SHA it attests to, but the tree id is content-addressed:
# it still matches on the final head as long as the suite itself did not change.
TESTS_TREE="$(git -C "$REPO" rev-parse HEAD:tests/live)"
STAMP="$(date -u +%Y%m%d-%H%M%S)"
OUT="$REPO/docs/e2e_results/live-deploy-infra-${SHORT_SHA}-${STAMP}.md"
JUNIT="$(mktemp)"
LOG="$(mktemp)"
ALLOCS="$(mktemp)"
trap 'rm -f "$JUNIT" "$LOG" "$ALLOCS"' EXIT

# The only allocation rows this suite creates. Anything left under this name
# after the run is a leak its teardown missed.
export OWNED_SERVICE="live-test-deploy-infra"

allocations_report() {
    curl -sS -H "X-Internal-Key: ${INTERNAL_API_KEY}" "${API_URL}/api/allocations/" >"$ALLOCS"
    python3 - "$ALLOCS" <<'PY'
import json
import os
import sys

owned = os.environ["OWNED_SERVICE"]
with open(sys.argv[1]) as handle:
    rows = json.load(handle)
mine = [row for row in rows if owned in str(row.get("service_name"))]
print(f"total allocations: {len(rows)}")
print(f'rows named "{owned}": {len(mine)}')
for row in mine:
    print(f"  id={row['id']} port={row['port']} server={row.get('server_id')}")
PY
}

junit_report() {
    python3 - "$JUNIT" <<'PY'
import sys
import xml.etree.ElementTree as ET

suite = ET.parse(sys.argv[1]).getroot().find("testsuite")
for case in suite.iter("testcase"):
    state = "passed"
    for child in case:
        if child.tag in ("failure", "error", "skipped"):
            state = child.tag
    name = f"{case.get('classname').rsplit('.', 1)[-1]}.{case.get('name')}"
    print(f"| `{name}` | {state} | {float(case.get('time')):.2f}s |")
print()
print(
    f"tests={suite.get('tests')} failures={suite.get('failures')} "
    f"errors={suite.get('errors')} skipped={suite.get('skipped')}"
)
PY
}

echo "==> stack ${API_URL}, repo ${REPO} @ ${SHORT_SHA}"
health="$(curl -sS -o /dev/null -w '%{http_code}' "${API_URL}/health")"
before="$(allocations_report)"

set +e
(cd "$REPO" && uv run pytest tests/live/test_deploy_infra.py -v --tb=short \
    -p no:cacheprovider --junitxml="$JUNIT") >"$LOG" 2>&1
RC=$?
set -e

after="$(allocations_report)"
results="$(junit_report)"
dirty="$(git -C "$REPO" status --porcelain | wc -l | tr -d ' ')"

mkdir -p "$(dirname "$OUT")"
cat >"$OUT" <<EOF
# Live evidence: deploy-infra prerequisite suite

Generated by \`scripts/live_deploy_infra_evidence.sh\` at ${STAMP} UTC.

CI cannot run this suite — it needs a managed server, a reachable VPS and the
allocation API — so this artifact is how the run is verified. Reproduce it with
a stack up and \`make test-live N=deploy_infra\`.

## What was tested

- SHA under test: \`${SHA}\`
- \`tests/live\` tree: \`${TESTS_TREE}\`
- Uncommitted files in the tree at run time: ${dirty}
- Stack: \`${API_URL}\`, \`GET /health\` -> ${health}
- Stack checkout: \`${ORCHESTRATOR_ROOT}\`
- pytest exit code: ${RC}

Verify this artifact describes the suite you are reviewing:
\`git rev-parse HEAD:tests/live\` must print the tree id above. Committing the
artifact moves HEAD past the SHA under test, but the tree id only changes if the
suite itself changes.

## Per-test results

| test | result | time |
| --- | --- | --- |
${results}

\`skipped\` would mean the suite never reached a managed server, so the SSH and
allocation tests have to read \`passed\` for this run to prove anything.

## Allocation state

The suite allocates a port named \`${OWNED_SERVICE}\` and releases it in a
\`finally\`. Rows under that name after the run would be a leak.

Before:

\`\`\`
${before}
\`\`\`

After:

\`\`\`
${after}
\`\`\`

## Full output

\`\`\`
$(cat "$LOG")
\`\`\`
EOF

echo "==> wrote ${OUT#"$REPO"/} (pytest rc=${RC})"
exit "$RC"
