"""add_server_health_metrics_and_history_table

Revision ID: 0d322ff94bfd
Revises: 42e0acc86b20
Create Date: 2026-03-17 00:40:29.543860

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0d322ff94bfd"
down_revision: str | None = "42e0acc86b20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "server_metrics_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("server_handle", sa.String(length=255), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["server_handle"],
            ["servers.handle"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_server_metrics_history_handle_recorded",
        "server_metrics_history",
        ["server_handle", "recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_server_metrics_history_recorded_at"),
        "server_metrics_history",
        ["recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_server_metrics_history_server_handle"),
        "server_metrics_history",
        ["server_handle"],
        unique=False,
    )
    op.add_column("servers", sa.Column("cpu_usage_pct", sa.Float(), nullable=True))
    op.add_column("servers", sa.Column("load_avg_1m", sa.Float(), nullable=True))
    op.add_column("servers", sa.Column("load_avg_5m", sa.Float(), nullable=True))
    op.add_column("servers", sa.Column("load_avg_15m", sa.Float(), nullable=True))
    op.add_column("servers", sa.Column("network_rx_errors", sa.BigInteger(), nullable=True))
    op.add_column("servers", sa.Column("network_tx_errors", sa.BigInteger(), nullable=True))
    op.add_column("servers", sa.Column("container_count_running", sa.Integer(), nullable=True))
    op.add_column("servers", sa.Column("container_count_total", sa.Integer(), nullable=True))
    op.add_column("servers", sa.Column("uptime_seconds", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("servers", "uptime_seconds")
    op.drop_column("servers", "container_count_total")
    op.drop_column("servers", "container_count_running")
    op.drop_column("servers", "network_tx_errors")
    op.drop_column("servers", "network_rx_errors")
    op.drop_column("servers", "load_avg_15m")
    op.drop_column("servers", "load_avg_5m")
    op.drop_column("servers", "load_avg_1m")
    op.drop_column("servers", "cpu_usage_pct")
    op.drop_index(
        op.f("ix_server_metrics_history_server_handle"), table_name="server_metrics_history"
    )
    op.drop_index(
        op.f("ix_server_metrics_history_recorded_at"), table_name="server_metrics_history"
    )
    op.drop_index("ix_server_metrics_history_handle_recorded", table_name="server_metrics_history")
    op.drop_table("server_metrics_history")
    # ### end Alembic commands ###
