"""Add server provisioning models and status

Revision ID: 12025dcae8ea
Revises: 545290cbb320
Create Date: 2025-12-24 19:07:52.739562

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "12025dcae8ea"
down_revision: str | None = "545290cbb320"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incidents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("server_handle", sa.String(length=255), nullable=False),
        sa.Column("incident_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("affected_services", sa.JSON(), nullable=False),
        sa.Column("recovery_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["server_handle"],
            ["servers.handle"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incidents_server_handle"), "incidents", ["server_handle"], unique=False
    )
    op.add_column("servers", sa.Column("last_health_check", sa.DateTime(), nullable=True))
    op.add_column(
        "servers",
        sa.Column("provisioning_attempts", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column("servers", sa.Column("last_incident", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("username", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("first_name", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("last_name", sa.String(length=255), nullable=True))
    op.add_column(
        "users", sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column(
        "users",
        sa.Column("last_seen", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("users", "last_seen")
    op.drop_column("users", "is_admin")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "username")
    op.drop_column("servers", "last_incident")
    op.drop_column("servers", "provisioning_attempts")
    op.drop_column("servers", "last_health_check")
    op.drop_index(op.f("ix_incidents_server_handle"), table_name="incidents")
    op.drop_table("incidents")
    # ### end Alembic commands ###
