"""add unique constraints for analytics upserts

Revision ID: 1e075b24917f
Revises: 622e11af498f
Create Date: 2026-03-20 20:49:22.252887

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e075b24917f"
down_revision: str | None = "622e11af498f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analytics_daily_project_date"), table_name="analytics_daily")
    op.create_unique_constraint(
        "uq_analytics_daily_project_date", "analytics_daily", ["project_id", "date"]
    )
    op.drop_index(op.f("ix_analytics_hourly_project_service_bucket"), table_name="analytics_hourly")
    op.create_unique_constraint(
        "uq_analytics_hourly_project_service_bucket",
        "analytics_hourly",
        ["project_id", "service_name", "bucket"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_analytics_hourly_project_service_bucket", "analytics_hourly", type_="unique"
    )
    op.create_index(
        op.f("ix_analytics_hourly_project_service_bucket"),
        "analytics_hourly",
        ["project_id", "service_name", "bucket"],
        unique=False,
    )
    op.drop_constraint("uq_analytics_daily_project_date", "analytics_daily", type_="unique")
    op.create_index(
        op.f("ix_analytics_daily_project_date"),
        "analytics_daily",
        ["project_id", "date"],
        unique=False,
    )
    # ### end Alembic commands ###
