"""add_application_health_fields_and_history

Revision ID: 254100cacd05
Revises: 0d322ff94bfd
Create Date: 2026-03-17 09:40:29.434736

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "254100cacd05"
down_revision: str | None = "0d322ff94bfd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("applications", sa.Column("response_time_ms", sa.Integer(), nullable=True))
    op.add_column(
        "applications", sa.Column("ssl_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("applications", sa.Column("uptime_pct_24h", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "uptime_pct_24h")
    op.drop_column("applications", "ssl_expires_at")
    op.drop_column("applications", "response_time_ms")
    # ### end Alembic commands ###
