"""add_llm_provider_fields_to_agent_configs

Revision ID: 2ac76ac9438e
Revises: 4e5b24357d81
Create Date: 2025-12-25 21:58:27.675070

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ac76ac9438e"
down_revision: str | None = "4e5b24357d81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server_default for backward compatibility
    op.add_column(
        "agent_configs",
        sa.Column(
            "llm_provider", sa.String(length=50), server_default="openrouter", nullable=False
        ),
    )
    op.add_column(
        "agent_configs",
        sa.Column(
            "model_identifier",
            sa.String(length=200),
            server_default="openai/gpt-4o",
            nullable=False,
        ),
    )
    op.add_column(
        "agent_configs", sa.Column("openrouter_site_url", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "agent_configs", sa.Column("openrouter_app_name", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_configs", "openrouter_app_name")
    op.drop_column("agent_configs", "openrouter_site_url")
    op.drop_column("agent_configs", "model_identifier")
    op.drop_column("agent_configs", "llm_provider")
    # ### end Alembic commands ###
