"""add acceptance_criteria to repositories

Revision ID: 36105dfd58c3
Revises: 83a7bd3dd57e
Create Date: 2026-03-19 21:29:26.421983

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "36105dfd58c3"
down_revision: str | None = "83a7bd3dd57e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("repositories", sa.Column("acceptance_criteria", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repositories", "acceptance_criteria")
    # ### end Alembic commands ###
