"""sync model drift

Revision ID: 4e96ae47d969
Revises: 6cca2fda6c83
Create Date: 2026-03-14 21:59:32.639357

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4e96ae47d969"
down_revision: str | None = "6cca2fda6c83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_project_id"), table_name="runs")
    op.drop_index(op.f("ix_tasks_status"), table_name="runs")
    op.drop_index(op.f("ix_tasks_type"), table_name="runs")
    op.drop_index(op.f("ix_tasks_user_id"), table_name="runs")
    op.drop_index(op.f("ix_tasks_work_item_id"), table_name="runs")
    op.create_index(op.f("ix_runs_project_id"), "runs", ["project_id"], unique=False)
    op.create_index(op.f("ix_runs_status"), "runs", ["status"], unique=False)
    op.create_index(op.f("ix_runs_task_id"), "runs", ["task_id"], unique=False)
    op.create_index(op.f("ix_runs_type"), "runs", ["type"], unique=False)
    op.create_index(op.f("ix_runs_user_id"), "runs", ["user_id"], unique=False)
    op.alter_column(
        "service_deployments",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_service_deployments_status"), table_name="service_deployments")
    op.create_index(
        op.f("ix_service_deployments_result"), "service_deployments", ["result"], unique=False
    )
    op.create_index(op.f("ix_stories_status"), "stories", ["status"], unique=False)
    op.drop_index(op.f("ix_work_item_events_work_item_id"), table_name="task_events")
    op.create_index(op.f("ix_task_events_task_id"), "task_events", ["task_id"], unique=False)
    op.alter_column(
        "tasks",
        "need_e2e",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "tasks",
        "failure_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_work_items_priority"), table_name="tasks")
    op.drop_index(op.f("ix_work_items_project_id"), table_name="tasks")
    op.drop_index(op.f("ix_work_items_status"), table_name="tasks")
    op.create_index(op.f("ix_tasks_priority"), "tasks", ["priority"], unique=False)
    op.create_index(op.f("ix_tasks_project_id"), "tasks", ["project_id"], unique=False)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_project_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_priority"), table_name="tasks")
    op.create_index(op.f("ix_work_items_status"), "tasks", ["status"], unique=False)
    op.create_index(op.f("ix_work_items_project_id"), "tasks", ["project_id"], unique=False)
    op.create_index(op.f("ix_work_items_priority"), "tasks", ["priority"], unique=False)
    op.alter_column(
        "tasks",
        "failure_metadata",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "tasks",
        "need_e2e",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.drop_index(op.f("ix_task_events_task_id"), table_name="task_events")
    op.create_index(
        op.f("ix_work_item_events_work_item_id"), "task_events", ["task_id"], unique=False
    )
    op.drop_index(op.f("ix_stories_status"), table_name="stories")
    op.drop_index(op.f("ix_service_deployments_result"), table_name="service_deployments")
    op.create_index(
        op.f("ix_service_deployments_status"), "service_deployments", ["result"], unique=False
    )
    op.alter_column(
        "service_deployments",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_runs_user_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_type"), table_name="runs")
    op.drop_index(op.f("ix_runs_task_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_status"), table_name="runs")
    op.drop_index(op.f("ix_runs_project_id"), table_name="runs")
    op.create_index(op.f("ix_tasks_work_item_id"), "runs", ["task_id"], unique=False)
    op.create_index(op.f("ix_tasks_user_id"), "runs", ["user_id"], unique=False)
    op.create_index(op.f("ix_tasks_type"), "runs", ["type"], unique=False)
    op.create_index(op.f("ix_tasks_status"), "runs", ["status"], unique=False)
    op.create_index(op.f("ix_tasks_project_id"), "runs", ["project_id"], unique=False)
    # ### end Alembic commands ###
