"""add disk capacity and usage fields

Revision ID: 545290cbb320
Revises: dd956fd031cf
Create Date: 2025-12-24 01:59:15.627878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545290cbb320'
down_revision: Union[str, None] = 'dd956fd031cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('capacity_disk_mb', sa.Integer(), nullable=False, server_default='10240'))
    op.add_column('servers', sa.Column('used_ram_mb', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('servers', sa.Column('used_disk_mb', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('servers', sa.Column('os_template', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'os_template')
    op.drop_column('servers', 'used_disk_mb')
    op.drop_column('servers', 'used_ram_mb')
    op.drop_column('servers', 'capacity_disk_mb')
    # ### end Alembic commands ###
