"""add analytics tables hourly daily known_users

Revision ID: 622e11af498f
Revises: 6c222830541c
Create Date: 2026-03-20 20:45:49.908876

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "622e11af498f"
down_revision: str | None = "6c222830541c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_daily",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_requests", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("unique_users", sa.Integer(), nullable=False),
        sa.Column("new_users", sa.Integer(), nullable=False),
        sa.Column("dau", sa.Integer(), nullable=False),
        sa.Column("returning_users", sa.Integer(), nullable=False),
        sa.Column("p95_ms", sa.Float(), nullable=True),
        sa.Column("error_rate", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_analytics_daily_project_date", "analytics_daily", ["project_id", "date"], unique=False
    )
    op.create_index(
        op.f("ix_analytics_daily_project_id"), "analytics_daily", ["project_id"], unique=False
    )
    op.create_table(
        "analytics_hourly",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("service_name", sa.String(length=100), nullable=False),
        sa.Column("bucket", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_requests", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("unique_users", sa.Integer(), nullable=False),
        sa.Column("new_users", sa.Integer(), nullable=False),
        sa.Column("p50_ms", sa.Float(), nullable=True),
        sa.Column("p95_ms", sa.Float(), nullable=True),
        sa.Column("p99_ms", sa.Float(), nullable=True),
        sa.Column("top_endpoints", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_analytics_hourly_project_bucket",
        "analytics_hourly",
        ["project_id", "bucket"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_hourly_project_id"), "analytics_hourly", ["project_id"], unique=False
    )
    op.create_index(
        "ix_analytics_hourly_project_service_bucket",
        "analytics_hourly",
        ["project_id", "service_name", "bucket"],
        unique=False,
    )
    op.create_table(
        "analytics_known_users",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("user_id_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("project_id", "user_id_hash"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("analytics_known_users")
    op.drop_index("ix_analytics_hourly_project_service_bucket", table_name="analytics_hourly")
    op.drop_index(op.f("ix_analytics_hourly_project_id"), table_name="analytics_hourly")
    op.drop_index("ix_analytics_hourly_project_bucket", table_name="analytics_hourly")
    op.drop_table("analytics_hourly")
    op.drop_index(op.f("ix_analytics_daily_project_id"), table_name="analytics_daily")
    op.drop_index("ix_analytics_daily_project_date", table_name="analytics_daily")
    op.drop_table("analytics_daily")
    # ### end Alembic commands ###
