"""add pr_number to stories

Revision ID: 6c222830541c
Revises: 78be95f450e0
Create Date: 2026-03-20 04:13:37.861844

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6c222830541c"
down_revision: str | None = "78be95f450e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stories", sa.Column("pr_number", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stories", "pr_number")
    # ### end Alembic commands ###
