"""add_service_deployments_table

Revision ID: 73b707900b42
Revises: 12025dcae8ea
Create Date: 2025-12-24 20:26:55.705933

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "73b707900b42"
down_revision: str | None = "12025dcae8ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_deployments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("service_name", sa.String(), nullable=False),
        sa.Column("server_handle", sa.String(length=255), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("deployed_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("deployment_info", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["server_handle"], ["servers.handle"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_deployments_project_id"),
        "service_deployments",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_deployments_server_handle"),
        "service_deployments",
        ["server_handle"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_deployments_status"), "service_deployments", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_deployments_status"), table_name="service_deployments")
    op.drop_index(op.f("ix_service_deployments_server_handle"), table_name="service_deployments")
    op.drop_index(op.f("ix_service_deployments_project_id"), table_name="service_deployments")
    op.drop_table("service_deployments")
    # ### end Alembic commands ###
