"""add_application_health_history_table

Revision ID: 73f6083e4563
Revises: 254100cacd05
Create Date: 2026-03-17 09:42:04.825481

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "73f6083e4563"
down_revision: str | None = "254100cacd05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_health_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_app_health_history_app_recorded",
        "application_health_history",
        ["application_id", "recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_health_history_application_id"),
        "application_health_history",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_health_history_recorded_at"),
        "application_health_history",
        ["recorded_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_application_health_history_recorded_at"), table_name="application_health_history"
    )
    op.drop_index(
        op.f("ix_application_health_history_application_id"),
        table_name="application_health_history",
    )
    op.drop_index("ix_app_health_history_app_recorded", table_name="application_health_history")
    op.drop_table("application_health_history")
    # ### end Alembic commands ###
