"""add bot_username to repositories

Revision ID: 78be95f450e0
Revises: 36105dfd58c3
Create Date: 2026-03-19 21:36:16.876855

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "78be95f450e0"
down_revision: str | None = "36105dfd58c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("repositories", sa.Column("bot_username", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repositories", "bot_username")
    # ### end Alembic commands ###
