"""add server management fields

Revision ID: 7d3377ca9b21
Revises: fdadf53d8a54
Create Date: 2025-12-24 00:42:15.851173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3377ca9b21'
down_revision: Union[str, None] = 'fdadf53d8a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('is_managed', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('servers', sa.Column('status', sa.String(length=50), nullable=False, server_default='active'))
    op.add_column('servers', sa.Column('notes', sa.String(), nullable=True))
    op.drop_column('servers', 'capacity_cpu')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('capacity_cpu', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('servers', 'notes')
    op.drop_column('servers', 'status')
    op.drop_column('servers', 'is_managed')
    # ### end Alembic commands ###
