"""add story_id to runs

Revision ID: 83a7bd3dd57e
Revises: 66e254ca3c49
Create Date: 2026-03-19 17:23:56.358999

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "83a7bd3dd57e"
down_revision: str | None = "66e254ca3c49"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runs", sa.Column("story_id", sa.String(length=255), nullable=True))
    op.create_index(op.f("ix_runs_story_id"), "runs", ["story_id"], unique=False)
    op.create_foreign_key(None, "runs", "stories", ["story_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "runs", type_="foreignkey")
    op.drop_index(op.f("ix_runs_story_id"), table_name="runs")
    op.drop_column("runs", "story_id")
    # ### end Alembic commands ###
