"""add_repository_url_to_projects

Revision ID: 8d88a99e06d5
Revises: 2df4b21abbbe
Create Date: 2025-12-30 11:11:03.980289

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8d88a99e06d5"
down_revision: str | None = "2df4b21abbbe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("repository_url", sa.String(length=512), nullable=True))
    op.drop_index(
        op.f("rag_chunks_embedding_idx"),
        table_name="rag_chunks",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    op.drop_index(op.f("rag_chunks_tsv_idx"), table_name="rag_chunks", postgresql_using="gin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("rag_chunks_tsv_idx"), "rag_chunks", ["tsv"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        op.f("rag_chunks_embedding_idx"),
        "rag_chunks",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    op.drop_column("projects", "repository_url")
    # ### end Alembic commands ###
