"""add_project_spec_field

Revision ID: 9a92199fda5f
Revises: 3b7b3d21a9f2
Create Date: 2025-12-26 22:03:41.365948

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9a92199fda5f"
down_revision: str | None = "3b7b3d21a9f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("project_spec", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "project_spec")
    # ### end Alembic commands ###
