"""add milestones table and work_items milestone_id

Revision ID: a6ac4f8437b9
Revises: b4c5d6e7f8a9
Create Date: 2026-03-07 14:56:10.489928

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a6ac4f8437b9"
down_revision: str | None = "b4c5d6e7f8a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "milestones",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("project_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("parent_id", sa.String(length=255), nullable=True),
        sa.Column("created_by", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["milestones.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_milestones_project_id"), "milestones", ["project_id"], unique=False)
    op.create_index(op.f("ix_milestones_status"), "milestones", ["status"], unique=False)
    op.add_column("work_items", sa.Column("milestone_id", sa.String(length=255), nullable=True))
    op.create_index(
        op.f("ix_work_items_milestone_id"), "work_items", ["milestone_id"], unique=False
    )
    op.create_foreign_key(
        "fk_work_items_milestone_id", "work_items", "milestones", ["milestone_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_work_items_milestone_id", "work_items", type_="foreignkey")
    op.drop_index(op.f("ix_work_items_milestone_id"), table_name="work_items")
    op.drop_column("work_items", "milestone_id")
    op.drop_index(op.f("ix_milestones_status"), table_name="milestones")
    op.drop_index(op.f("ix_milestones_project_id"), table_name="milestones")
    op.drop_table("milestones")
    # ### end Alembic commands ###
