"""Add_ProjectStatus_and_github_repo_id

Revision ID: a8a0638f378f
Revises: 73b707900b42
Create Date: 2025-12-25 00:11:52.663848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a0638f378f'
down_revision: Union[str, None] = '73b707900b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('github_repo_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'github_repo_id')
    # ### end Alembic commands ###
