"""drop stale domains and telegram_bots tables

Revision ID: d9d613e270c2
Revises: a6ac4f8437b9
Create Date: 2026-03-07 15:24:53.632837

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d9d613e270c2"
down_revision: str | None = "a6ac4f8437b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("domains")
    op.drop_table("telegram_bots")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_bots",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("token_enc", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("username", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("tg_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("project_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("telegram_bots_project_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("telegram_bots_pkey")),
    )
    op.create_table(
        "domains",
        sa.Column("domain_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("provider", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("domains_project_id_fkey")
        ),
        sa.PrimaryKeyConstraint("domain_name", name=op.f("domains_pkey")),
    )
    # ### end Alembic commands ###
