"""add capacity_cpu to servers

Revision ID: dd956fd031cf
Revises: 7d3377ca9b21
Create Date: 2025-12-24 01:39:35.557340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd956fd031cf'
down_revision: Union[str, None] = '7d3377ca9b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('capacity_cpu', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'capacity_cpu')
    # ### end Alembic commands ###
