##############################################################################
# THIS FILE IS GENERATED BY THE FRAMEWORK. DO NOT EDIT MANUALLY.
# CHANGES WILL BE OVERWRITTEN.
##############################################################################

# AUTO-GENERATED BY SERVICE-TEMPLATE - DO NOT EDIT
"""Package identities used to generate this product contract."""

ACTIVE_PACKAGES: list[dict[str, str]] = []
