"""Central QA against a product that carries a kit package.

Three things are asserted here, and they are the three the card asks for.

* A package's scheduled behaviour reaches the run the same way a service's
  does. The name is read off the criteria, retained by criteria preparation,
  named to the executor and accepted by `fire_job` — a package prefix is a
  name, not a new mechanism, and the dispatch rule that decides a service's
  behaviour decides a package's unchanged.
* The connection check and the acceptance checks are answered from the
  deployed product: the packages this run states are the ones its own
  generated contract records on the target, cross-checked against the backend
  manifest allowlist it booted with.
* A contract that cannot be read is never "no packages". Every unreadable,
  truncated, half-present or inconsistent artifact fails the run before an
  executor starts, because a check that examined nothing must not pass.
"""

from __future__ import annotations

from types import SimpleNamespace

import pytest

from shared.contracts.acceptance import parse_scheduled_behaviours
from src.agents.qa.acceptance import prepare_central_qa_criteria
from src.agents.qa.packages import (
    ACTIVE_PACKAGE_CONTRACT,
    BACKEND_MANIFEST,
    GENERATED_JOB_REGISTRY,
    ActivePackage,
    PackageActivation,
    PackageContractUnreadable,
    active_package_facts,
    parse_active_packages,
    parse_job_owners,
    parse_listed_packages,
)
from src.agents.qa.tools import QAJobsCapability
from src.consumers._qa_runner import run_package_activation_checks, scheduled_behaviour_facts
from src.consumers._qa_target import QATargetError

# What the kit's package-contract generator writes into a product that installed
# `reminders`, in the shape it writes it.
ACTIVE_PACKAGES_SOURCE = '''\
# AUTO-GENERATED BY SERVICE-TEMPLATE - DO NOT EDIT
"""Package identities used to generate this product contract."""

ACTIVE_PACKAGES: list[dict[str, str]] = [
    {
        "manifest_sha256": "8f14e45fceea167a5a36dedd4bea2543aaa1f2c3d4e5f60718293a4b5c6d7e8f",
        "name": "reminders",
        "version": "0.1.0",
    }
]
'''

PACKAGE_FREE_SOURCE = '''\
# AUTO-GENERATED BY SERVICE-TEMPLATE - DO NOT EDIT
"""Package identities used to generate this product contract."""

ACTIVE_PACKAGES: list[dict[str, str]] = []
'''

# The generated job registry of the same product: the loader attributes a
# package's job to `package:<name>`, a service's job to the service.
JOB_REGISTRY_SOURCE = """\
# AUTO-GENERATED BY SERVICE-TEMPLATE - DO NOT EDIT
from __future__ import annotations

import json

JOB_SCHEMAS: dict[str, object] = json.loads(
    r'''{
    "daily_digest": {},
    "reminders.tick": {}
}'''
)

JOB_SCHEMA_SOURCES: dict[str, str] = json.loads(
    r'''{
    "daily_digest": "backend",
    "reminders.tick": "package:reminders"
}'''
)

JOB_CAPABILITY_PROVIDERS: dict[str, list[str]] = {}
"""

EMPTY_JOB_REGISTRY_SOURCE = """\
# AUTO-GENERATED BY SERVICE-TEMPLATE - DO NOT EDIT
from __future__ import annotations

JOB_SCHEMAS: dict[str, object] = {}

JOB_SCHEMA_SOURCES: dict[str, str] = {}

JOB_CAPABILITY_PROVIDERS: dict[str, list[str]] = {}
"""

MANIFEST_WITH_PACKAGE = "name: backend\npackages:\n  - reminders\n"
MANIFEST_WITHOUT_PACKAGES = "name: backend\npackages: []\n"
MANIFEST_BEFORE_PACKAGES = "name: backend\n"

DEPLOYED_URL = "http://1.2.3.4:8000"

# The one package the kit publishes, and the behaviour it declares.
REMINDERS = ActivePackage(
    name="reminders",
    version="0.1.0",
    manifest_sha256="8f14e45fceea167a5a36dedd4bea2543aaa1f2c3d4e5f60718293a4b5c6d7e8f",
)


class FakeSession:
    """A target that answers a contained read of the deployment's own files.

    A path it does not hold answers the way the target's contained read
    answers a file that is not there, so "absent" and "unreadable" reach the
    probe as the two different things they are.
    """

    def __init__(self, files: dict[str, str], *, unreadable: dict[str, str] | None = None) -> None:
        self.files = files
        self.unreadable = unreadable or {}
        self.read: list[str] = []

    async def read_file(self, path: str, *, max_bytes: int = 8000):
        self.read.append(path)
        if path in self.unreadable:
            raise QATargetError(self.unreadable[path])
        if path not in self.files:
            return SimpleNamespace(exit_status=5, stdout="", stderr=f"notafile:{path}")
        return SimpleNamespace(exit_status=0, stdout=self.files[path][:max_bytes], stderr="")


def _package_product(**overrides: str) -> FakeSession:
    files = {
        BACKEND_MANIFEST: MANIFEST_WITH_PACKAGE,
        ACTIVE_PACKAGE_CONTRACT: ACTIVE_PACKAGES_SOURCE,
        GENERATED_JOB_REGISTRY: JOB_REGISTRY_SOURCE,
    }
    files.update(overrides)
    return FakeSession(files)


class TestTheGeneratedContractIsReadAsWritten:
    """The parsers read the artifacts the kit's generators write."""

    def test_the_active_package_set_carries_name_version_and_digest(self):
        assert parse_active_packages(ACTIVE_PACKAGES_SOURCE) == (REMINDERS,)

    def test_a_product_with_no_package_records_an_empty_set(self):
        assert parse_active_packages(PACKAGE_FREE_SOURCE) == ()

    def test_the_manifest_allowlist_is_read_from_the_product(self):
        assert parse_listed_packages(MANIFEST_WITH_PACKAGE) == ("reminders",)
        assert parse_listed_packages(MANIFEST_WITHOUT_PACKAGES) == ()

    def test_a_manifest_that_predates_packages_declares_nothing_either_way(self):
        assert parse_listed_packages(MANIFEST_BEFORE_PACKAGES) is None

    def test_every_job_is_attributed_to_the_declarer_the_product_recorded(self):
        owners = parse_job_owners(JOB_REGISTRY_SOURCE)

        assert owners == {"daily_digest": "backend", "reminders.tick": "package:reminders"}
        assert PackageActivation(packages=(), listed=(), jobs=owners).package_jobs == {
            "reminders.tick": "reminders"
        }

    def test_a_product_whose_registry_is_empty_attributes_no_job_to_a_package(self):
        assert parse_job_owners(EMPTY_JOB_REGISTRY_SOURCE) == {}


class TestAContractWithNothingInItIsNotAnAnswer:
    """Every unreadable artifact fails closed instead of reading as package-free."""

    @pytest.mark.parametrize(
        "source",
        [
            "",
            '"""Package identities."""\n',
            "ACTIVE_PACKAGES = load_them()\n",
            'ACTIVE_PACKAGES: list[dict[str, str]] = [\n    {"name": "reminders",\n',
            'ACTIVE_PACKAGES: list[dict[str, str]] = {"reminders": "0.1.0"}\n',
            'ACTIVE_PACKAGES: list[dict[str, str]] = [{"name": "reminders"}]\n',
            'ACTIVE_PACKAGES: list[dict[str, str]] = [{"name": "", "version": "0.1.0",'
            ' "manifest_sha256": "abc"}]\n',
        ],
    )
    def test_an_unreadable_active_package_contract_is_refused(self, source):
        with pytest.raises(PackageContractUnreadable):
            parse_active_packages(source)

    @pytest.mark.parametrize(
        "source",
        ["- not a mapping\n", "packages: reminders\n", "packages:\n  - 3\n", "packages:\n  - ''\n"],
    )
    def test_an_unreadable_manifest_allowlist_is_refused(self, source):
        with pytest.raises(PackageContractUnreadable):
            parse_listed_packages(source)

    @pytest.mark.parametrize(
        "source",
        [
            "JOB_SCHEMAS: dict[str, object] = {}\n",
            "JOB_SCHEMA_SOURCES: dict[str, str] = read_them()\n",
            "JOB_SCHEMA_SOURCES: dict[str, str] = json.loads(r'''{\"a\": ''')\n",
            'JOB_SCHEMA_SOURCES: dict[str, str] = {"a": 3}\n',
        ],
    )
    def test_an_unreadable_job_registry_is_refused(self, source):
        with pytest.raises(PackageContractUnreadable):
            parse_job_owners(source)


class TestTheProbeReadsTheDeployedProduct:
    """What the run may state about packages, it read off this deployment."""

    async def test_the_active_set_is_read_from_the_products_own_contract(self):
        session = _package_product()

        outcome = await run_package_activation_checks(session)

        assert outcome.failure is None
        assert outcome.activation == PackageActivation(
            packages=(REMINDERS,),
            listed=("reminders",),
            jobs={"daily_digest": "backend", "reminders.tick": "package:reminders"},
        )
        assert session.read[0] == BACKEND_MANIFEST
        assert ACTIVE_PACKAGE_CONTRACT in session.read

    async def test_a_package_free_product_is_left_exactly_as_it_was(self):
        session = FakeSession(
            {
                BACKEND_MANIFEST: MANIFEST_WITHOUT_PACKAGES,
                ACTIVE_PACKAGE_CONTRACT: PACKAGE_FREE_SOURCE,
            }
        )

        outcome = await run_package_activation_checks(session)

        assert outcome.activation is None
        assert outcome.failure is None
        # Nothing was read that a package-free run does not need: the generated
        # job registry belongs to the package path only.
        assert GENERATED_JOB_REGISTRY not in session.read

    async def test_a_product_from_a_template_without_packages_is_left_as_it_was(self):
        session = FakeSession({BACKEND_MANIFEST: MANIFEST_BEFORE_PACKAGES})

        outcome = await run_package_activation_checks(session)

        assert outcome.activation is None
        assert outcome.failure is None

    async def test_a_deployment_with_no_backend_manifest_states_nothing_about_packages(self):
        session = FakeSession({})

        outcome = await run_package_activation_checks(session)

        assert outcome.activation is None
        assert outcome.failure is None


class TestAPackageCheckWithNothingToExamineFails:
    """The failure mode the kit's own sprint records: a check that examined nothing."""

    async def test_a_listed_package_with_no_generated_contract_fails_the_run(self):
        session = FakeSession({BACKEND_MANIFEST: MANIFEST_WITH_PACKAGE})

        outcome = await run_package_activation_checks(session)

        assert outcome.activation is None
        assert outcome.failure is not None
        assert outcome.failure.passed is False
        assert ACTIVE_PACKAGE_CONTRACT in outcome.failure.summary + outcome.failure.report

    async def test_a_truncated_generated_contract_fails_the_run(self):
        session = _package_product(
            **{ACTIVE_PACKAGE_CONTRACT: ACTIVE_PACKAGES_SOURCE[: len(ACTIVE_PACKAGES_SOURCE) // 2]}
        )

        outcome = await run_package_activation_checks(session)

        assert outcome.activation is None
        assert outcome.failure is not None and outcome.failure.passed is False

    async def test_a_generated_set_that_disagrees_with_the_allowlist_fails_the_run(self):
        session = _package_product(**{ACTIVE_PACKAGE_CONTRACT: PACKAGE_FREE_SOURCE})

        outcome = await run_package_activation_checks(session)

        assert outcome.activation is None
        assert outcome.failure is not None and outcome.failure.passed is False
        assert "reminders" in outcome.failure.report

    async def test_a_contract_the_target_refused_to_read_is_not_read_as_package_free(self):
        session = FakeSession(
            {BACKEND_MANIFEST: MANIFEST_WITH_PACKAGE},
            unreadable={ACTIVE_PACKAGE_CONTRACT: "permission denied"},
        )

        outcome = await run_package_activation_checks(session)

        assert outcome.activation is None
        assert outcome.failure is not None and outcome.failure.passed is False

    async def test_a_package_product_with_no_generated_job_registry_fails_the_run(self):
        session = FakeSession(
            {
                BACKEND_MANIFEST: MANIFEST_WITH_PACKAGE,
                ACTIVE_PACKAGE_CONTRACT: ACTIVE_PACKAGES_SOURCE,
            }
        )

        outcome = await run_package_activation_checks(session)

        assert outcome.activation is None
        assert outcome.failure is not None and outcome.failure.passed is False
        assert GENERATED_JOB_REGISTRY in outcome.failure.report


class TestWhatTheRunIsToldAboutItsPackages:
    """The facts the executor is given, and the two things they refuse to say."""

    def test_the_connection_check_is_answered_from_the_booted_product(self):
        facts = active_package_facts(
            PackageActivation(packages=(REMINDERS,), listed=("reminders",), jobs={}),
            deployed_url=DEPLOYED_URL,
        )
        stated = "\n".join(facts)

        assert "reminders 0.1.0" in stated
        assert REMINDERS.manifest_sha256[:12] in stated
        assert ACTIVE_PACKAGE_CONTRACT in stated
        assert "startup" in stated
        # The check is asserted from the running product, not re-run by anyone.
        assert "refuses to boot" in stated
        assert "do not install" in stated.lower()

    def test_the_acceptance_checks_are_bound_to_this_deployment(self):
        facts = active_package_facts(
            PackageActivation(packages=(REMINDERS,), listed=("reminders",), jobs={}),
            deployed_url=DEPLOYED_URL,
        )
        stated = "\n".join(facts)

        assert DEPLOYED_URL in stated
        assert "fixture" in stated
        assert "replica" in stated
        # A check that could not be made against this deployment is a failure.
        assert "failed check" in stated

    def test_a_package_behaviour_is_named_with_its_package(self):
        facts = active_package_facts(
            PackageActivation(
                packages=(REMINDERS,),
                listed=("reminders",),
                jobs={"daily_digest": "backend", "reminders.tick": "package:reminders"},
            ),
            deployed_url=DEPLOYED_URL,
            fireable_behaviours=("reminders.tick",),
        )
        stated = "\n".join(facts)

        assert "reminders.tick" in stated
        assert "dispatch record is not" in stated

    def test_a_behaviour_the_deployed_product_does_not_declare_is_named_as_a_failure(self):
        facts = active_package_facts(
            PackageActivation(
                packages=(REMINDERS,),
                listed=("reminders",),
                jobs={"daily_digest": "backend", "reminders.tick": "package:reminders"},
            ),
            deployed_url=DEPLOYED_URL,
            fireable_behaviours=("reminders.tick", "reminders.sweep"),
        )
        stated = "\n".join(facts)

        assert "reminders.sweep" in stated
        assert "fails" in stated


class TestAPackagesBehaviourUsesTheChainAServicesBehaviourUses:
    """The same four steps, with a package-prefixed name in them."""

    CRITERIA = (
        "- GET /health returns 200\n"
        '- FIRE JOB reminders.tick WITH {"at": "2026-09-07T10:00:00Z"} THEN the bot '
        "sends the reminder text to its owner\n"
    )

    def test_the_criteria_declare_the_package_behaviour_and_it_is_retained(self):
        prepared = prepare_central_qa_criteria(self.CRITERIA)
        behaviours = parse_scheduled_behaviours(prepared.criteria)

        assert prepared.adjustments == ()
        assert [one.name for one in behaviours] == ["reminders.tick"]
        assert behaviours[0].arguments == {"at": "2026-09-07T10:00:00Z"}

    def test_the_run_is_told_the_package_behaviour_by_name_and_the_dispatch_rule(self):
        behaviours = parse_scheduled_behaviours(self.CRITERIA)

        facts = "\n".join(scheduled_behaviour_facts(behaviours, fireable=True))

        assert "reminders.tick" in facts
        assert "not evidence that anything consumed it or that the behaviour ran" in facts

    def test_the_package_behaviour_is_in_the_runs_declared_set(self):
        behaviours = parse_scheduled_behaviours(self.CRITERIA)
        jobs = QAJobsCapability(
            base_url=DEPLOYED_URL,
            capability="never-leaves-the-host",  # noqa: S106
            fired_by_product="project-1",
            fired_by_run="qa-run-1",
            behaviours=tuple(behaviours),
        )

        assert jobs.names == ["reminders.tick"]
        assert jobs.behaviour("reminders.tick") is not None
        assert jobs.behaviour("reminders.sweep") is None
