"""Central QA against a product that carries a kit package.

Three things are asserted here, and they are the three the card asks for.

* A package's scheduled behaviour reaches the run the same way a service's
  does. The name is read off the criteria, retained by criteria preparation,
  named to the executor and accepted by `fire_job` — a package prefix is a
  name, not a new mechanism, and the dispatch rule that decides a service's
  behaviour decides a package's unchanged.
* The connection check and the acceptance checks are answered from the
  deployed product: the packages this run states are the ones its own
  generated contract records on the target, cross-checked against the backend
  manifest allowlist it booted with.
* A contract that cannot be read is never "no packages". Every unreadable,
  truncated, half-present or inconsistent artifact fails the run before an
  executor starts, because a check that examined nothing must not pass.
"""

from __future__ import annotations

from collections.abc import Sequence
from types import SimpleNamespace

import pytest

from shared.contracts.acceptance import ScheduledBehaviourCriterion, parse_scheduled_behaviours
from src.agents.qa.acceptance import prepare_central_qa_criteria
from src.agents.qa.packages import (
    ACTIVE_PACKAGE_CONTRACT,
    BACKEND_MANIFEST,
    GENERATED_JOB_REGISTRY,
    ActivePackage,
    PackageActivation,
    PackageContractUnreadable,
    active_package_facts,
    behaviour_check_name,
    connection_check,
    connection_check_name,
    observable_paths,
    observation_answers,
    observation_tokens,
    parse_active_packages,
    parse_job_owners,
    parse_listed_packages,
)
from src.agents.qa.tools import QAJobsCapability, build_qa_callables
from src.consumers._qa_runner import (
    PackageAcceptance,
    QAResult,
    apply_package_acceptance,
    run_package_acceptance_checks,
    run_package_activation_checks,
    scheduled_behaviour_facts,
)
from src.consumers._qa_target import (
    QACapabilities,
    QATargetError,
    RemoteResult,
    loopback_http_status,
)
from src.consumers._qa_workspace import BehaviourEvidence, ProductObservation, QAWorkspace

# What the kit's package-contract generator writes into a product that installed
# `reminders`, in the shape it writes it.
ACTIVE_PACKAGES_SOURCE = '''\
# AUTO-GENERATED BY SERVICE-TEMPLATE - DO NOT EDIT
"""Package identities used to generate this product contract."""

ACTIVE_PACKAGES: list[dict[str, str]] = [
    {
        "manifest_sha256": "8f14e45fceea167a5a36dedd4bea2543aaa1f2c3d4e5f60718293a4b5c6d7e8f",
        "name": "reminders",
        "version": "0.1.0",
    }
]
'''

PACKAGE_FREE_SOURCE = '''\
# AUTO-GENERATED BY SERVICE-TEMPLATE - DO NOT EDIT
"""Package identities used to generate this product contract."""

ACTIVE_PACKAGES: list[dict[str, str]] = []
'''

# The generated job registry of the same product: the loader attributes a
# package's job to `package:<name>`, a service's job to the service.
JOB_REGISTRY_SOURCE = """\
# AUTO-GENERATED BY SERVICE-TEMPLATE - DO NOT EDIT
from __future__ import annotations

import json

JOB_SCHEMAS: dict[str, object] = json.loads(
    r'''{
    "daily_digest": {},
    "reminders.tick": {}
}'''
)

JOB_SCHEMA_SOURCES: dict[str, str] = json.loads(
    r'''{
    "daily_digest": "backend",
    "reminders.tick": "package:reminders"
}'''
)

JOB_CAPABILITY_PROVIDERS: dict[str, list[str]] = {}
"""

EMPTY_JOB_REGISTRY_SOURCE = """\
# AUTO-GENERATED BY SERVICE-TEMPLATE - DO NOT EDIT
from __future__ import annotations

JOB_SCHEMAS: dict[str, object] = {}

JOB_SCHEMA_SOURCES: dict[str, str] = {}

JOB_CAPABILITY_PROVIDERS: dict[str, list[str]] = {}
"""

MANIFEST_WITH_PACKAGE = "name: backend\npackages:\n  - reminders\n"
MANIFEST_WITHOUT_PACKAGES = "name: backend\npackages: []\n"
MANIFEST_BEFORE_PACKAGES = "name: backend\n"

DEPLOYED_URL = "http://1.2.3.4:8000"

# The one package the kit publishes, and the behaviour it declares.
REMINDERS = ActivePackage(
    name="reminders",
    version="0.1.0",
    manifest_sha256="8f14e45fceea167a5a36dedd4bea2543aaa1f2c3d4e5f60718293a4b5c6d7e8f",
)


class FakeSession:
    """A target that answers a contained read of the deployment's own files.

    A path it does not hold answers the way the target's contained read
    answers a file that is not there, so "absent" and "unreadable" reach the
    probe as the two different things they are.
    """

    def __init__(self, files: dict[str, str], *, unreadable: dict[str, str] | None = None) -> None:
        self.files = files
        self.unreadable = unreadable or {}
        self.read: list[str] = []

    async def read_file(self, path: str, *, max_bytes: int = 8000):
        self.read.append(path)
        if path in self.unreadable:
            raise QATargetError(self.unreadable[path])
        if path not in self.files:
            return SimpleNamespace(exit_status=5, stdout="", stderr=f"notafile:{path}")
        return SimpleNamespace(exit_status=0, stdout=self.files[path][:max_bytes], stderr="")


def _package_product(**overrides: str) -> FakeSession:
    files = {
        BACKEND_MANIFEST: MANIFEST_WITH_PACKAGE,
        ACTIVE_PACKAGE_CONTRACT: ACTIVE_PACKAGES_SOURCE,
        GENERATED_JOB_REGISTRY: JOB_REGISTRY_SOURCE,
    }
    files.update(overrides)
    return FakeSession(files)


class TestTheGeneratedContractIsReadAsWritten:
    """The parsers read the artifacts the kit's generators write."""

    def test_the_active_package_set_carries_name_version_and_digest(self):
        assert parse_active_packages(ACTIVE_PACKAGES_SOURCE) == (REMINDERS,)

    def test_a_product_with_no_package_records_an_empty_set(self):
        assert parse_active_packages(PACKAGE_FREE_SOURCE) == ()

    def test_the_manifest_allowlist_is_read_from_the_product(self):
        assert parse_listed_packages(MANIFEST_WITH_PACKAGE) == ("reminders",)
        assert parse_listed_packages(MANIFEST_WITHOUT_PACKAGES) == ()

    def test_a_manifest_that_predates_packages_declares_nothing_either_way(self):
        assert parse_listed_packages(MANIFEST_BEFORE_PACKAGES) is None

    def test_every_job_is_attributed_to_the_declarer_the_product_recorded(self):
        owners = parse_job_owners(JOB_REGISTRY_SOURCE)

        assert owners == {"daily_digest": "backend", "reminders.tick": "package:reminders"}
        assert PackageActivation(packages=(), listed=(), jobs=owners).package_jobs == {
            "reminders.tick": "reminders"
        }

    def test_a_product_whose_registry_is_empty_attributes_no_job_to_a_package(self):
        assert parse_job_owners(EMPTY_JOB_REGISTRY_SOURCE) == {}


class TestAContractWithNothingInItIsNotAnAnswer:
    """Every unreadable artifact fails closed instead of reading as package-free."""

    @pytest.mark.parametrize(
        "source",
        [
            "",
            '"""Package identities."""\n',
            "ACTIVE_PACKAGES = load_them()\n",
            'ACTIVE_PACKAGES: list[dict[str, str]] = [\n    {"name": "reminders",\n',
            'ACTIVE_PACKAGES: list[dict[str, str]] = {"reminders": "0.1.0"}\n',
            'ACTIVE_PACKAGES: list[dict[str, str]] = [{"name": "reminders"}]\n',
            'ACTIVE_PACKAGES: list[dict[str, str]] = [{"name": "", "version": "0.1.0",'
            ' "manifest_sha256": "abc"}]\n',
        ],
    )
    def test_an_unreadable_active_package_contract_is_refused(self, source):
        with pytest.raises(PackageContractUnreadable):
            parse_active_packages(source)

    @pytest.mark.parametrize(
        "source",
        ["- not a mapping\n", "packages: reminders\n", "packages:\n  - 3\n", "packages:\n  - ''\n"],
    )
    def test_an_unreadable_manifest_allowlist_is_refused(self, source):
        with pytest.raises(PackageContractUnreadable):
            parse_listed_packages(source)

    @pytest.mark.parametrize(
        "source",
        [
            "JOB_SCHEMAS: dict[str, object] = {}\n",
            "JOB_SCHEMA_SOURCES: dict[str, str] = read_them()\n",
            "JOB_SCHEMA_SOURCES: dict[str, str] = json.loads(r'''{\"a\": ''')\n",
            'JOB_SCHEMA_SOURCES: dict[str, str] = {"a": 3}\n',
        ],
    )
    def test_an_unreadable_job_registry_is_refused(self, source):
        with pytest.raises(PackageContractUnreadable):
            parse_job_owners(source)


class TestTheProbeReadsTheDeployedProduct:
    """What the run may state about packages, it read off this deployment."""

    async def test_the_active_set_is_read_from_the_products_own_contract(self):
        session = _package_product()

        outcome = await run_package_activation_checks(session)

        assert outcome.failure is None
        assert outcome.activation == PackageActivation(
            packages=(REMINDERS,),
            listed=("reminders",),
            jobs={"daily_digest": "backend", "reminders.tick": "package:reminders"},
        )
        assert session.read[0] == BACKEND_MANIFEST
        assert ACTIVE_PACKAGE_CONTRACT in session.read

    async def test_a_package_free_product_is_left_exactly_as_it_was(self):
        session = FakeSession(
            {
                BACKEND_MANIFEST: MANIFEST_WITHOUT_PACKAGES,
                ACTIVE_PACKAGE_CONTRACT: PACKAGE_FREE_SOURCE,
            }
        )

        outcome = await run_package_activation_checks(session)

        assert outcome.activation is None
        assert outcome.failure is None
        # Nothing was read that a package-free run does not need: the generated
        # job registry belongs to the package path only.
        assert GENERATED_JOB_REGISTRY not in session.read

    async def test_a_product_from_a_template_without_packages_is_left_as_it_was(self):
        session = FakeSession({BACKEND_MANIFEST: MANIFEST_BEFORE_PACKAGES})

        outcome = await run_package_activation_checks(session)

        assert outcome.activation is None
        assert outcome.failure is None

    async def test_a_deployment_with_no_backend_manifest_states_nothing_about_packages(self):
        session = FakeSession({})

        outcome = await run_package_activation_checks(session)

        assert outcome.activation is None
        assert outcome.failure is None


class TestAPackageCheckWithNothingToExamineFails:
    """The failure mode the kit's own sprint records: a check that examined nothing."""

    async def test_a_listed_package_with_no_generated_contract_fails_the_run(self):
        session = FakeSession({BACKEND_MANIFEST: MANIFEST_WITH_PACKAGE})

        outcome = await run_package_activation_checks(session)

        assert outcome.activation is None
        assert outcome.failure is not None
        assert outcome.failure.passed is False
        assert ACTIVE_PACKAGE_CONTRACT in outcome.failure.summary + outcome.failure.report

    async def test_a_truncated_generated_contract_fails_the_run(self):
        session = _package_product(
            **{ACTIVE_PACKAGE_CONTRACT: ACTIVE_PACKAGES_SOURCE[: len(ACTIVE_PACKAGES_SOURCE) // 2]}
        )

        outcome = await run_package_activation_checks(session)

        assert outcome.activation is None
        assert outcome.failure is not None and outcome.failure.passed is False

    async def test_a_generated_set_that_disagrees_with_the_allowlist_fails_the_run(self):
        session = _package_product(**{ACTIVE_PACKAGE_CONTRACT: PACKAGE_FREE_SOURCE})

        outcome = await run_package_activation_checks(session)

        assert outcome.activation is None
        assert outcome.failure is not None and outcome.failure.passed is False
        assert "reminders" in outcome.failure.report

    async def test_a_contract_the_target_refused_to_read_is_not_read_as_package_free(self):
        session = FakeSession(
            {BACKEND_MANIFEST: MANIFEST_WITH_PACKAGE},
            unreadable={ACTIVE_PACKAGE_CONTRACT: "permission denied"},
        )

        outcome = await run_package_activation_checks(session)

        assert outcome.activation is None
        assert outcome.failure is not None and outcome.failure.passed is False

    async def test_a_package_product_with_no_generated_job_registry_fails_the_run(self):
        session = FakeSession(
            {
                BACKEND_MANIFEST: MANIFEST_WITH_PACKAGE,
                ACTIVE_PACKAGE_CONTRACT: ACTIVE_PACKAGES_SOURCE,
            }
        )

        outcome = await run_package_activation_checks(session)

        assert outcome.activation is None
        assert outcome.failure is not None and outcome.failure.passed is False
        assert GENERATED_JOB_REGISTRY in outcome.failure.report


class TestWhatTheRunIsToldAboutItsPackages:
    """The facts the executor is given, and the two things they refuse to say."""

    def test_the_connection_check_is_answered_from_the_booted_product(self):
        facts = active_package_facts(
            PackageActivation(packages=(REMINDERS,), listed=("reminders",), jobs={}),
            deployed_url=DEPLOYED_URL,
        )
        stated = "\n".join(facts)

        assert "reminders 0.1.0" in stated
        assert REMINDERS.manifest_sha256[:12] in stated
        assert ACTIVE_PACKAGE_CONTRACT in stated
        assert "startup" in stated
        # The check is asserted from the running product, not re-run by anyone.
        assert "refuses to boot" in stated
        assert "do not install" in stated.lower()

    def test_the_acceptance_checks_are_bound_to_this_deployment(self):
        facts = active_package_facts(
            PackageActivation(packages=(REMINDERS,), listed=("reminders",), jobs={}),
            deployed_url=DEPLOYED_URL,
        )
        stated = "\n".join(facts)

        assert DEPLOYED_URL in stated
        assert "fixture" in stated
        assert "replica" in stated
        # A check that could not be made against this deployment is a failure.
        assert "failed check" in stated

    def test_a_package_behaviour_is_named_with_its_package(self):
        facts = active_package_facts(
            PackageActivation(
                packages=(REMINDERS,),
                listed=("reminders",),
                jobs={"daily_digest": "backend", "reminders.tick": "package:reminders"},
            ),
            deployed_url=DEPLOYED_URL,
            fireable_behaviours=("reminders.tick",),
        )
        stated = "\n".join(facts)

        assert "reminders.tick" in stated
        assert "dispatch record is not" in stated

    def test_a_behaviour_the_deployed_product_does_not_declare_is_named_as_a_failure(self):
        facts = active_package_facts(
            PackageActivation(
                packages=(REMINDERS,),
                listed=("reminders",),
                jobs={"daily_digest": "backend", "reminders.tick": "package:reminders"},
            ),
            deployed_url=DEPLOYED_URL,
            fireable_behaviours=("reminders.tick", "reminders.sweep"),
        )
        stated = "\n".join(facts)

        assert "reminders.sweep" in stated
        assert "fails" in stated


class TestAPackagesBehaviourUsesTheChainAServicesBehaviourUses:
    """The same four steps, with a package-prefixed name in them.

    The observable names a route on the deployed product, which is what a
    package behaviour criterion owes: a bot-only observable parses and fires
    just as well, but binds to nothing and fails its row, so the example a
    criterion is written from is the one the platform accepts.
    """

    CRITERIA = (
        "- GET /health returns 200\n"
        '- FIRE JOB reminders.tick WITH {"at": "2026-09-07T10:00:00Z"} THEN GET '
        "/reminders?user_ref=42 shows the reminder as emitted\n"
    )

    def test_the_criteria_declare_the_package_behaviour_and_it_is_retained(self):
        prepared = prepare_central_qa_criteria(self.CRITERIA)
        behaviours = parse_scheduled_behaviours(prepared.criteria)

        assert prepared.adjustments == ()
        assert [one.name for one in behaviours] == ["reminders.tick"]
        assert behaviours[0].arguments == {"at": "2026-09-07T10:00:00Z"}

    def test_the_run_is_told_the_package_behaviour_by_name_and_the_dispatch_rule(self):
        behaviours = parse_scheduled_behaviours(self.CRITERIA)

        facts = "\n".join(scheduled_behaviour_facts(behaviours, fireable=True))

        assert "reminders.tick" in facts
        assert "not evidence that anything consumed it or that the behaviour ran" in facts

    def test_the_package_behaviour_is_in_the_runs_declared_set(self):
        behaviours = parse_scheduled_behaviours(self.CRITERIA)
        jobs = QAJobsCapability(
            base_url=DEPLOYED_URL,
            capability="never-leaves-the-host",  # noqa: S106
            fired_by_product="project-1",
            fired_by_run="qa-run-1",
            behaviours=tuple(behaviours),
        )

        assert jobs.names == ["reminders.tick"]
        assert jobs.behaviour("reminders.tick") is not None
        assert jobs.behaviour("reminders.sweep") is None


class _LoopbackSession:
    """A target whose loopback probe answers with one recorded curl result."""

    def __init__(self, stdout: str) -> None:
        self.capabilities = QACapabilities(
            deployed_url=DEPLOYED_URL,
            physical_root="/srv/deployments/app",
            containers=frozenset({"app-backend-1"}),
            loopback_ports=frozenset({8000}),
        )
        self._stdout = stdout

    async def localhost_http_get(self, port: int, path: str) -> RemoteResult:
        return RemoteResult(exit_status=0, stdout=self._stdout, stderr="")


class FakeWorkspace:
    """The runner's own record of what this run fired, read back, and read.

    Every map carries the point in the run where the product answered, because
    an observation made before the fire is an observation of something else.
    """

    def __init__(
        self,
        fired: dict[str, int] | None = None,
        evidence: dict[str, int] | None = None,
        observations: Sequence[tuple[int, str, str]] = (),
        *,
        dispatch_status: str = "dispatched",
    ) -> None:
        self.fired_behaviours = fired or {}
        self.behaviour_evidence = {
            name: BehaviourEvidence(position=position, dispatch_status=dispatch_status)
            for name, position in (evidence or {}).items()
        }
        self.observations = [
            ProductObservation(position=position, tool=tool, subject=subject)
            for position, tool, subject in observations
        ]


TICK = ScheduledBehaviourCriterion(
    name="reminders.tick",
    arguments={"at": "2026-09-07T10:00:00Z"},
    observable="GET /reminders?user_ref=42 shows the reminder as emitted",
)
SWEEP = ScheduledBehaviourCriterion(
    name="reminders.sweep",
    observable="GET /reminders?user_ref=42 no longer shows the cancelled reminder",
)
#: A read of the package's own route, after the fire.
READ = (4, "http_get", "/reminders?user_ref=42")
SWEEP_READ = (7, "http_get", "/reminders?user_ref=42")
JUDGED = {
    "name": "reminders.tick delivers the reminder",
    "pass": True,
    "detail": "GET /reminders?user_ref=42 showed the reminder as emitted",
}
JUDGED_SWEEP = {
    "name": "reminders.sweep clears it",
    "pass": True,
    "detail": "GET /reminders?user_ref=42 no longer lists it",
}
TICK_ROW = behaviour_check_name("reminders", "reminders.tick")
SWEEP_ROW = behaviour_check_name("reminders", "reminders.sweep")


def _acceptance(
    *,
    declared: tuple[ScheduledBehaviourCriterion, ...] = (),
    owned: tuple[str, ...] = ("reminders.tick",),
    fireable: bool = True,
):
    return PackageAcceptance(
        activation=PackageActivation(
            packages=(REMINDERS,),
            listed=("reminders",),
            jobs=dict.fromkeys(owned, "package:reminders"),
        ),
        checks=(connection_check(REMINDERS),),
        declared={"reminders": declared},
        owned={"reminders": owned},
        fireable=fireable,
    )


def _row(result, name: str) -> dict:
    return next(check for check in result.checks if check["name"] == name)


class TestWhichReadAnswersACriterion:
    """The criterion says where to look; the platform does not guess."""

    def test_a_route_the_observable_names_is_the_read_it_asks_for(self):
        assert observable_paths(TICK.observable) == ("/reminders",)
        assert observation_answers(TICK.observable, "http_get", "/reminders?user_ref=42")
        assert observation_answers(TICK.observable, "http_get", "/reminders/7")

    def test_an_unrelated_path_is_not_that_read(self):
        assert not observation_answers(TICK.observable, "http_get", "/health")
        assert not observation_answers(TICK.observable, "telegram_probe", "@bot")

    def test_an_observable_naming_no_route_can_be_bound_to_no_read(self):
        """An observable that names nothing to read is answered by nothing."""
        prose = "the owner receives the reminder text"

        assert observable_paths(prose) == ()
        assert not observation_answers(prose, "telegram_probe", "@weather_bot")
        assert not observation_answers(prose, "http_get", "/reminders")
        assert not observation_answers(prose, "http_get", "/health")

    def test_a_check_may_quote_the_request_the_run_made(self):
        tokens = observation_tokens("http_get", "/reminders?user_ref=42")

        assert "/reminders" in tokens
        assert "/reminders?user_ref=42" in tokens
        assert "telegram" in observation_tokens("telegram_probe", "@weather_bot")


class TestABehaviourRestsOnAReadOfTheProduct:
    """Fire, read the product's own output, and a check resting on that read.

    What the platform establishes is that the work was done and the executor
    judged it. The observable is prose an architect wrote; no runner-side rule
    reads English, and the row says so rather than claiming a proof.
    """

    def test_a_verdict_that_performed_nothing_fails_and_names_the_check(self):
        result = apply_package_acceptance(
            QAResult(passed=True, checks=[], summary="OK"),
            _acceptance(declared=(TICK,)),
            FakeWorkspace(),
        )

        assert result.passed is False
        assert "accepted no fire" in _row(result, TICK_ROW)["detail"]

    def test_a_fire_with_no_read_of_the_product_does_not_pass(self):
        result = apply_package_acceptance(
            QAResult(passed=True, checks=[JUDGED], summary="OK"),
            _acceptance(declared=(TICK,)),
            FakeWorkspace({"reminders.tick": 3}),
        )

        assert result.passed is False
        detail = _row(result, TICK_ROW)["detail"]
        assert "made no successful read of /reminders" in detail
        assert TICK.observable in detail

    def test_the_fires_own_receipt_is_not_a_read_of_the_product(self):
        """job_evidence answers with the core's record of the dispatch, and no more."""
        result = apply_package_acceptance(
            QAResult(passed=True, checks=[JUDGED], summary="OK"),
            _acceptance(declared=(TICK,)),
            FakeWorkspace({"reminders.tick": 3}, {"reminders.tick": 4}),
        )

        assert result.passed is False
        assert "made no successful read" in _row(result, TICK_ROW)["detail"]

    def test_an_unrelated_read_is_not_this_behaviours_read(self):
        result = apply_package_acceptance(
            QAResult(passed=True, checks=[JUDGED], summary="OK"),
            _acceptance(declared=(TICK,)),
            FakeWorkspace({"reminders.tick": 3}, observations=[(4, "http_get", "/health")]),
        )

        assert result.passed is False
        assert "made no successful read of /reminders" in _row(result, TICK_ROW)["detail"]

    def test_a_read_before_the_fire_is_a_read_of_something_else(self):
        result = apply_package_acceptance(
            QAResult(passed=True, checks=[JUDGED], summary="OK"),
            _acceptance(declared=(TICK,)),
            FakeWorkspace({"reminders.tick": 5}, observations=[(2, *READ[1:])]),
        )

        assert result.passed is False
        assert _row(result, TICK_ROW)["pass"] is False

    def test_a_check_that_rests_on_no_read_this_run_made_does_not_pass(self):
        unbound = {"name": "reminders.tick succeeded", "pass": True, "detail": "the job fired"}

        result = apply_package_acceptance(
            QAResult(passed=True, checks=[unbound], summary="OK"),
            _acceptance(declared=(TICK,)),
            FakeWorkspace({"reminders.tick": 3}, observations=[READ]),
        )

        assert result.passed is False
        assert "quotes the read it rests on" in _row(result, TICK_ROW)["detail"]

    def test_a_failed_check_for_the_behaviour_is_not_a_judgement_in_its_favour(self):
        result = apply_package_acceptance(
            QAResult(passed=False, checks=[{**JUDGED, "pass": False}]),
            _acceptance(declared=(TICK,)),
            FakeWorkspace({"reminders.tick": 3}, observations=[READ]),
        )

        assert result.passed is False
        assert "quotes the read it rests on" in _row(result, TICK_ROW)["detail"]

    def test_a_command_the_product_never_delivered_settles_the_row(self):
        """Not a requirement, but a refutation: the event never left the core."""
        result = apply_package_acceptance(
            QAResult(passed=True, checks=[JUDGED], summary="OK"),
            _acceptance(declared=(TICK,)),
            FakeWorkspace(
                {"reminders.tick": 2},
                {"reminders.tick": 3},
                observations=[READ],
                dispatch_status="undelivered",
            ),
        )

        assert result.passed is False
        detail = _row(result, TICK_ROW)["detail"]
        assert "dispatch_status=undelivered" in detail
        assert "the event was never emitted" in detail

    def test_a_criterion_that_names_no_route_fails_rather_than_binding_anything(self):
        """The reviewer's route-less hole: a fire, a healthy unrelated read, a confident check."""
        prose = ScheduledBehaviourCriterion(
            name="reminders.tick", observable="the owner receives the reminder text"
        )
        claimed = {
            "name": "reminders.tick succeeded",
            "pass": True,
            "detail": "after reminders.tick, GET /health was 200",
        }

        result = apply_package_acceptance(
            QAResult(passed=True, checks=[claimed], summary="OK"),
            _acceptance(declared=(prose,)),
            FakeWorkspace({"reminders.tick": 1}, observations=[(2, "http_get", "/health")]),
        )

        assert result.passed is False
        detail = _row(result, TICK_ROW)["detail"]
        assert "names no route on the deployed product that this run could read" in detail
        assert prose.observable in detail

    def test_a_behaviour_fired_read_and_judged_passes_and_says_on_what(self):
        result = apply_package_acceptance(
            QAResult(passed=True, checks=[JUDGED], summary="OK"),
            _acceptance(declared=(TICK,)),
            FakeWorkspace({"reminders.tick": 3}, observations=[READ]),
        )

        assert result.passed is True
        detail = _row(result, TICK_ROW)["detail"]
        assert "http_get /reminders?user_ref=42" in detail
        assert TICK.observable in detail
        assert JUDGED["name"] in detail
        # The row states the limit of what the platform established.
        assert "the work was done and that the executor judged it" in detail
        assert "not a mechanical proof" in detail


class TestEveryDeclaredBehaviourGetsItsOwnRow:
    """Two behaviours are two results; one of them going unfired is a failure."""

    def test_a_second_declared_behaviour_is_not_silently_omitted(self):
        result = apply_package_acceptance(
            QAResult(passed=True, checks=[JUDGED], summary="OK"),
            _acceptance(declared=(TICK, SWEEP), owned=("reminders.sweep", "reminders.tick")),
            FakeWorkspace({"reminders.tick": 2}, observations=[READ]),
        )

        assert result.passed is False
        assert _row(result, TICK_ROW)["pass"] is True
        assert _row(result, SWEEP_ROW)["pass"] is False
        assert SWEEP_ROW in result.summary

    def test_both_behaviours_performed_carry_two_passing_rows(self):
        result = apply_package_acceptance(
            QAResult(passed=True, checks=[JUDGED, JUDGED_SWEEP], summary="OK"),
            _acceptance(declared=(TICK, SWEEP), owned=("reminders.sweep", "reminders.tick")),
            FakeWorkspace(
                {"reminders.tick": 2, "reminders.sweep": 6},
                observations=[READ, SWEEP_READ],
            ),
        )

        assert result.passed is True
        assert [_row(result, TICK_ROW)["pass"], _row(result, SWEEP_ROW)["pass"]] == [True, True]

    def test_a_package_that_declares_no_behaviour_owes_no_behaviour_check(self):
        result = apply_package_acceptance(
            QAResult(passed=True, checks=[], summary="OK"), _acceptance(owned=()), FakeWorkspace()
        )

        assert result.passed is True
        assert [check["name"] for check in result.checks] == [connection_check_name("reminders")]

    def test_a_criteria_set_that_names_no_package_behaviour_fails_one_row(self):
        result = apply_package_acceptance(
            QAResult(passed=True, checks=[]), _acceptance(), FakeWorkspace()
        )

        assert result.passed is False
        [failed] = [check for check in result.checks if not check["pass"]]
        assert failed["name"] == behaviour_check_name("reminders")
        assert "no FIRE JOB" in failed["detail"]

    def test_a_deployment_with_no_jobs_capability_says_so(self):
        result = apply_package_acceptance(
            QAResult(passed=True), _acceptance(declared=(TICK,), fireable=False), FakeWorkspace()
        )

        assert _row(result, TICK_ROW)["pass"] is False
        assert "no jobs capability" in _row(result, TICK_ROW)["detail"]

    def test_an_executor_row_of_the_same_name_is_not_a_second_route_to_a_verdict(self):
        """Only `_behaviour_row` writes a package behaviour row.

        An executor may submit a check called anything, including the exact
        name of a behaviour row. The runner's own row is still computed, still
        prepended, and still fails the run, so naming a row is not a way to
        write one.
        """
        counterfeit = {
            "name": TICK_ROW,
            "pass": True,
            "detail": "reminders.tick produced its observable",
        }

        result = apply_package_acceptance(
            QAResult(passed=True, checks=[counterfeit], summary="OK"),
            _acceptance(declared=(TICK,)),
            FakeWorkspace(),
        )

        assert result.passed is False
        assert _row(result, TICK_ROW)["pass"] is False
        assert "accepted no fire of it in this run" in _row(result, TICK_ROW)["detail"]
        assert TICK_ROW in result.summary

    def test_a_package_free_run_is_returned_exactly_as_it_was(self):
        verdict = QAResult(passed=True, checks=[{"name": "health", "pass": True, "detail": "200"}])

        result = apply_package_acceptance(verdict, None, FakeWorkspace())

        assert result.passed is True
        assert result.checks == [{"name": "health", "pass": True, "detail": "200"}]


class TestNoRouteIsInferredFromAPackagesName:
    """Protocol v1 does not bind a package's HTTP prefix to its name."""

    def test_the_run_owes_only_the_connection_row_deterministically(self):
        acceptance = run_package_acceptance_checks(
            PackageActivation(
                packages=(REMINDERS,),
                listed=("reminders",),
                jobs={"reminders.tick": "package:reminders"},
            ),
            criteria_behaviours=(TICK,),
        )

        assert [check["name"] for check in acceptance.checks] == [
            connection_check_name("reminders")
        ]
        assert acceptance.declared["reminders"] == (TICK,)
        assert acceptance.owned["reminders"] == ("reminders.tick",)

    def test_the_run_is_told_the_prefix_is_not_published_rather_than_guessed(self):
        stated = "\n".join(
            active_package_facts(
                PackageActivation(packages=(REMINDERS,), listed=("reminders",), jobs={}),
                deployed_url=DEPLOYED_URL,
            )
        )

        assert "no prefixed-route check is required of this run" in stated
        assert "none is inferred from the package's name" in stated


class TestOnlyASuccessfulReadIsAnObservation:
    """An error response is the product answering about the request, not about itself.

    The loopback probe runs curl without `--fail`, so a 500 comes back as exit
    status 0 with the status written into the output. Reading that status is
    what keeps a broken package route from standing in for a working one.
    """

    def test_the_loopback_probe_carries_the_status_it_received(self):
        assert loopback_http_status("{}\n<<qa-http-status:200>>") == 200
        assert loopback_http_status("error\n<<qa-http-status:500>>") == 500
        assert loopback_http_status("curl: (7) Failed to connect") is None

    def test_a_counterfeit_marker_in_the_body_does_not_answer_for_curl(self):
        """The route writes the body; only curl writes the last marker.

        A package route that answers 500 with a body containing the text of a
        200 marker would otherwise pass for a successful read of itself, which
        is the vacuous pass this whole path exists to refuse.
        """
        spoofed = "application failure <<qa-http-status:200>>\n<<qa-http-status:500>>"

        assert loopback_http_status(spoofed) == 500
        assert loopback_http_status("<<qa-http-status:200>>\n<<qa-http-status:404>>\n") == 404
        # A body that carries a marker and no curl marker after it is not a
        # status this probe received: the read is unanswered, not successful.
        assert loopback_http_status("<<qa-http-status:200>> trailing body") is None

    async def test_a_counterfeit_marker_route_is_not_recorded_as_a_read(self, tmp_path):
        workspace = QAWorkspace(path=tmp_path)
        workspace.trace_path.touch()
        calls = build_qa_callables(
            session=_LoopbackSession("boom <<qa-http-status:200>>\n<<qa-http-status:500>>"),
            workspace=workspace,
        )

        await calls["localhost_http_get"](8000, "/reminders")

        assert workspace.observations == []

    async def test_an_error_answer_on_a_loopback_route_is_not_recorded_as_a_read(self, tmp_path):
        workspace = QAWorkspace(path=tmp_path)
        workspace.trace_path.touch()
        calls = build_qa_callables(
            session=_LoopbackSession("<<qa-http-status:500>>"), workspace=workspace
        )

        await calls["localhost_http_get"](8000, "/reminders")

        assert workspace.observations == []

    async def test_a_successful_answer_on_a_loopback_route_is_recorded(self, tmp_path):
        workspace = QAWorkspace(path=tmp_path)
        workspace.trace_path.touch()
        calls = build_qa_callables(
            session=_LoopbackSession('{"reminders": []}\n<<qa-http-status:200>>'),
            workspace=workspace,
        )

        await calls["localhost_http_get"](8000, "/reminders")

        assert [(one.tool, one.subject) for one in workspace.observations] == [
            ("localhost_http_get", "/reminders")
        ]
