"""Generate the runtime registry from explicit service settings manifests."""

from __future__ import annotations

import json
from pathlib import Path

from framework.generators.base import BaseGenerator


class SettingsManifestGenerator(BaseGenerator):
    """Emit one deterministic, backend-consumable settings schema registry."""

    def generate(self) -> list[Path]:
        schemas: dict[str, object] = {}
        sources: dict[str, str] = {}
        for service_name, manifest in sorted(self.specs.manifests.items()):
            properties = manifest.settings_schema["properties"]
            for key, schema in sorted(properties.items()):
                if key in schemas:
                    msg = (
                        f"Setting '{key}' is declared by both '{sources[key]}' "
                        f"and '{service_name}'"
                    )
                    raise ValueError(msg)
                schemas[key] = schema
                sources[key] = service_name

        for service_dir in sorted((self.repo_root / "services").glob("*/")):
            if service_dir.name != "backend":
                continue
            output_file = service_dir / "src" / "generated" / "settings_schemas.py"
            content = self._render_content(schemas, sources)
            self.write_file(output_file, content)
            return [output_file]
        return []

    @staticmethod
    def _render_content(schemas: dict[str, object], sources: dict[str, str]) -> str:
        rendered_schemas = json.dumps(schemas, indent=4, sort_keys=True)
        rendered_sources = json.dumps(sources, indent=4, sort_keys=True)
        return (
            "# AUTO-GENERATED BY SERVICE-TEMPLATE - DO NOT EDIT\n"
            '\"\"\"Validated settings schemas declared by service manifests.\"\"\"\n\n'
            "from __future__ import annotations\n\n"
            f"SETTINGS_SCHEMAS: dict[str, object] = {rendered_schemas}\n\n"
            f"SETTINGS_SCHEMA_SOURCES: dict[str, str] = {rendered_sources}\n"
        )
