"""The level-1 change set has to survive the product's own gate, offline.

On the stand the scripted runner applies the change set, runs ``make setup`` and
commits with the product's ``.githooks`` armed. A change set that any of those
refuse costs a stand run to find out. This module applies the same change set to
the vendored render of the pinned kit and runs, right here, the product's own
gate over the result — with the *kit's own tooling*, at the same commit the
fixture resolves.

What is executed here, not described
------------------------------------

* the *runner's own parser and applier* — ``noop._SCRIPT`` is executed, not
  reimplemented, so the format this suite emits is judged by the code that will
  read it;
* ``make setup``'s own steps over the applied tree: ``python -m
  framework.generate``, then the kit's ``ruff format`` and ``ruff check --fix``;
* every check of the kit's ``make lint`` that the product's ``pre-push`` runs
  when Docker is unavailable — and the worker images carry no Docker, so that is
  the path the stand takes: ``ruff format --check``, ``ruff check``, ``xenon``,
  ``framework.spec.loader.validate_specs_cli``,
  ``framework.enforce_spec_compliance``,
  ``framework.lint.controller_sync.lint_controllers_cli`` and ``deptry`` for
  every service the change set touches (``make check-deps``);
* the generated settings registry the deployed endpoint reads back, produced by
  the real generator rather than asserted from the manifest alone.

``codegen-kit-tooling`` is a test-only dependency of this repository, pinned at
exactly the commit the fixture's own ``pyproject.toml`` resolves;
:func:`test_the_kit_tooling_is_pinned_to_the_commit_the_fixture_resolves` fails
if the two ever drift.

What it deliberately does not claim
-----------------------------------

Two checks of the product's gate need the *product's per-service virtualenvs*,
which do not exist in this tree and cannot be built offline:

* ``framework.lint.package_imports`` takes ``--site-packages`` from
  ``services/backend/.venv/bin/python``, so it has nothing to point at here;
* the kit's ``make tests <svc>`` runs ``services/<svc>/.venv/bin/pytest``.
  Materialising those environments means resolving and building the product's
  own dependency trees (``asyncpg``, ``psycopg``, ``faststream``,
  ``python-telegram-bot``) from the network inside a unit test, which would make
  this suite neither offline nor hermetic. They stay the stand's job — the
  scripted runner's ``push`` step runs them through ``pre-push``, and a failure
  there now names the step (see ``record_engineering_failure_steps``).

The ruff, xenon and deptry binaries are this repository's rather than the
product's pinned ones. The pristine fixture is therefore put through the same
gate in the same run, so a tool release that starts flagging the kit fails as a
baseline rather than as a defect of the change set.
"""

from __future__ import annotations

import importlib.util
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tomllib
from types import ModuleType

import jsonschema
import pytest
import yaml

from scripts.template_pin import TEMPLATE_PIN

REPO_ROOT = Path(__file__).resolve().parents[2]
LIVE_DIR = REPO_ROOT / "tests" / "live"
MARKER = "e2e-0f1e2d3c4b5a"
#: The extension story's marker. A second story of the same project gets its
#: own, so what the deployment answers cannot be the first story's answer.
EXTENSION_MARKER = "e2e-5a4b3c2d1e0f"
GENERATED_MARKER = "THIS FILE IS GENERATED BY THE FRAMEWORK"

#: Exactly the exclusion `make lint` passes to `ruff format --check`.
FORMAT_EXCLUDE = "*.md,.venv/**,**/.venv/**,services/**/migrations/**"
#: Exactly the thresholds and exclusion the kit's `make lint` passes to xenon.
XENON_ARGS = (
    "--max-absolute",
    "B",
    "--max-modules",
    "A",
    "--max-average",
    "A",
    "--exclude",
    "tests/*,services/*/tests/*",
)
#: The services `make check-deps` and `pre-push` run deptry for. The change set
#: touches both, so both are checked.
DEPTRY_SERVICES = ("backend", "tg_bot")

#: The two `make lint` steps that read the framework through a one-liner rather
#: than as a module, copied from the kit's Makefile so this runs what it runs.
VALIDATE_SPECS = (
    "from framework.spec.loader import validate_specs_cli; "
    "from framework.lib.env import get_repo_root; "
    "ok, msg = validate_specs_cli(get_repo_root()); print(msg); exit(0 if ok else 1)"
)
LINT_CONTROLLERS = (
    "from framework.lint.controller_sync import lint_controllers_cli; "
    "from framework.lib.env import get_repo_root; "
    "ok, msg = lint_controllers_cli(get_repo_root()); print(msg); exit(0 if ok else 1)"
)


def _load(name: str, path: Path) -> ModuleType:
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec and spec.loader, path
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


#: Variables that would let a checker see *this* repository while it judges the
#: product tree. `PYTHONPATH` is the load-bearing one: the offline sweep runs
#: pytest with the orchestrator root on it, which makes `services` and `shared`
#: importable — and deptry then reclassifies the product's own `services.*`
#: imports as a transitive dependency and reports 40 DEP003 violations that the
#: stand, where nothing but the product is importable, never sees. A checker
#: pointed at the product must see only the product.
FOREIGN_ENVIRONMENT = ("PYTHONPATH", "VIRTUAL_ENV")


def _product_environment(**overrides: str) -> dict[str, str]:
    environment = {
        key: value for key, value in os.environ.items() if key not in FOREIGN_ENVIRONMENT
    }
    environment.update(overrides)
    return environment


def _tool(
    tree: Path, name: str, *args: str, cwd: Path | None = None
) -> subprocess.CompletedProcess:
    executable = shutil.which(name)
    assert executable, f"{name} is not on PATH; run this suite through `uv run`"
    return subprocess.run(  # noqa: S603
        [executable, *args],
        cwd=cwd or tree,
        env=_product_environment(),
        capture_output=True,
        text=True,
        check=False,
    )


def _kit(tree: Path, *args: str) -> subprocess.CompletedProcess:
    """Run one of the kit's own tooling entry points against ``tree``.

    ``framework.lib.env.get_repo_root`` honours ``SERVICE_TEMPLATE_ROOT``, which
    is how the product's tooling is pointed at a checkout that is not the
    current repository.
    """
    return subprocess.run(  # noqa: S603
        [sys.executable, *args],
        cwd=tree,
        env=_product_environment(SERVICE_TEMPLATE_ROOT=str(tree), PYTHONPATH=str(tree)),
        capture_output=True,
        text=True,
        check=False,
    )


def _ruff(tree: Path, *args: str) -> subprocess.CompletedProcess:
    return _tool(tree, "ruff", *args)


def _ruff_format_check(tree: Path) -> subprocess.CompletedProcess:
    return _ruff(tree, "format", "--check", "--exclude", FORMAT_EXCLUDE, ".")


def _ruff_diagnostics(tree: Path) -> list[dict]:
    result = _ruff(tree, "check", "--output-format", "json", ".")
    assert result.stdout, result.stderr
    return json.loads(result.stdout)


def _product_gate(tree: Path) -> dict[str, subprocess.CompletedProcess]:
    """Every step of the kit's `make lint` this tree can answer for, by name.

    Keyed by step so a failure says which check of the product's gate refused,
    the same way the stand's evidence now names the runner step that failed.
    """
    results = {
        "ruff format --check": _ruff_format_check(tree),
        "ruff check": _ruff(tree, "check", "."),
        "xenon": _tool(tree, "xenon", *XENON_ARGS, "."),
        "validate-specs": _kit(tree, "-c", VALIDATE_SPECS),
        "enforce-spec-compliance": _kit(tree, "-m", "framework.enforce_spec_compliance"),
        "lint-controllers": _kit(tree, "-c", LINT_CONTROLLERS),
    }
    for service in DEPTRY_SERVICES:
        results[f"check-deps {service}"] = _tool(
            tree, "deptry", "src/", cwd=tree / "services" / service
        )
    return results


def _assert_gate_passes(results: dict[str, subprocess.CompletedProcess]) -> None:
    failed = {
        step: (result.stdout + result.stderr).strip()
        for step, result in results.items()
        if result.returncode != 0
    }

    assert failed == {}


def _make_setup(tree: Path) -> None:
    """The kit's own `make setup`, minus the `uv sync` steps this tree has no venvs for.

    Order matters and is the Makefile's: the generator writes first, then ruff
    formats and fixes what it wrote. Asserting the gate against a tree the
    generator never touched would be asserting against something the stand never
    has.
    """
    generated = _kit(tree, "-m", "framework.generate")
    assert generated.returncode == 0, generated.stdout + generated.stderr
    formatted = _ruff(tree, "format", "--extend-exclude", "*.md", ".")
    assert formatted.returncode == 0, formatted.stdout + formatted.stderr
    fixed = _ruff(tree, "check", "--fix", ".")
    assert fixed.returncode == 0, fixed.stdout + fixed.stderr


@pytest.fixture(scope="module")
def change_sets():
    module = _load("level1_change_set", LIVE_DIR / "level1_change_set.py")
    return module, module.build_level1_change_sets(MARKER, (TEMPLATE_PIN.source, TEMPLATE_PIN.ref))


@pytest.fixture(scope="module")
def runner_script() -> dict:
    """The scripted runner's own parser and applier, executed from its source.

    The runner ships as a ``python3 -c`` script embedded in ``noop.py``; running
    that source here is what makes this test judge the real format rather than a
    second implementation of it that can drift from it.
    """
    from worker_wrapper.runners.noop import _SCRIPT

    namespace: dict = {"__name__": "noop_runner_script"}
    exec(compile(_SCRIPT, "worker_wrapper/runners/noop.py", "exec"), namespace)  # noqa: S102
    return namespace


@pytest.fixture(scope="module")
def pristine_tree(tmp_path_factory) -> Path:
    """A writable copy of the pinned render, so the baseline can run the generator too."""
    tree = tmp_path_factory.mktemp("level1-pristine") / "product"
    shutil.copytree(TEMPLATE_PIN.fixture_path(), tree)
    return tree


@pytest.fixture(scope="module")
def applied_tree(tmp_path_factory, change_sets, runner_script) -> Path:
    """The pinned kit render with both of the story's change sets applied."""
    _, sets = change_sets
    tree = tmp_path_factory.mktemp("level1-kit") / "product"
    shutil.copytree(TEMPLATE_PIN.fixture_path(), tree)
    for description in (sets.backend_task_description(), sets.bot_task_description()):
        operations = runner_script["parse_change_set"](description)
        assert operations, "a task description carried no change set the runner recognises"
        runner_script["apply_change_set"](operations, str(tree))
    return tree


@pytest.fixture(scope="module")
def setup_tree(tmp_path_factory, applied_tree: Path) -> Path:
    """The applied tree the far side of `make setup` — what the hooks actually see."""
    tree = tmp_path_factory.mktemp("level1-setup") / "product"
    shutil.copytree(applied_tree, tree)
    _make_setup(tree)
    return tree


def test_the_kit_tooling_is_pinned_to_the_commit_the_fixture_resolves() -> None:
    """The gate is only honest while it runs the tooling the stand runs.

    The fixture's `pyproject.toml` is what the rendered product resolves
    `codegen-kit-tooling` from; this repository depends on the same commit so the
    checks below are the product's own. A pin moved on one side alone fails here.
    """
    ours = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    source = ours["tool"]["uv"]["sources"]["codegen-kit-tooling"]
    fixture = (TEMPLATE_PIN.fixture_path() / "pyproject.toml").read_text(encoding="utf-8")

    assert "codegen-kit-tooling" in ours["dependency-groups"]["dev"]
    assert f"codegen-product-kit.git@{source['rev']}" in fixture


def test_the_pinned_kit_passes_its_own_gate_before_the_change_set_touches_it(
    pristine_tree: Path,
) -> None:
    """The baseline, so a tool release is never mistaken for a bad change set."""
    _make_setup(pristine_tree)

    _assert_gate_passes(_product_gate(pristine_tree))


def test_the_applied_tree_passes_the_kit_s_own_gate(setup_tree: Path) -> None:
    """`make setup` then every `make lint` step `pre-push` runs without Docker.

    This is the check AC 7 exists for: `framework.enforce_spec_compliance` is
    what refuses an `APIRouter()` outside `app/api/routers/`, and it runs here
    rather than on the stand.
    """
    _assert_gate_passes(_product_gate(setup_tree))


def test_the_generated_registry_carries_the_product_setting(setup_tree: Path, change_sets) -> None:
    """The real generator, not the manifest, is asked what the deployment will read.

    The deployed endpoint reports `SETTINGS_SCHEMAS`, so what the live probe
    asserts — exactly one key ending in the setting's name, whose declared
    default is this run's marker — is checked here against the generator's own
    output.
    """
    module, sets = change_sets
    registry = _load(
        "level1_settings_schemas",
        setup_tree / "services/backend/src/generated/settings_schemas.py",
    )

    declaring = {
        key: schema
        for key, schema in registry.SETTINGS_SCHEMAS.items()
        if schema.get("default") == sets.marker
    }
    assert list(declaring) == [module.LEVEL1_SETTING_KEY]
    assert registry.SETTINGS_SCHEMA_SOURCES[module.LEVEL1_SETTING_KEY] == "backend"


def test_the_applied_tree_passes_the_kit_s_own_ruff(applied_tree: Path) -> None:
    """Before the generator runs, too: `make setup` lints what it was handed."""
    reported = [
        (diagnostic["code"], diagnostic["filename"], diagnostic["message"])
        for diagnostic in _ruff_diagnostics(applied_tree)
    ]

    assert reported == []


def test_the_applied_tree_is_already_formatted(applied_tree: Path) -> None:
    """`pre-commit` runs `make format` and then `git add -A`.

    A change set whose files reformat is not refused by the hook — it is silently
    rewritten, and the commit then carries something other than what this suite
    wrote. That is worth failing here rather than discovering as a diff.
    """
    result = _ruff_format_check(applied_tree)

    assert result.returncode == 0, result.stdout


def test_every_change_set_file_compiles(applied_tree: Path, change_sets) -> None:
    _, sets = change_sets

    for path in sets.paths:
        if path.endswith(".py"):
            source = (applied_tree / path).read_text(encoding="utf-8")
            compile(source, path, "exec")


def test_the_product_setting_is_declared_as_a_usable_json_schema(
    applied_tree: Path, change_sets
) -> None:
    """The manifest is what the framework generates `SETTINGS_SCHEMAS` from."""
    module, sets = change_sets
    manifest = yaml.safe_load((applied_tree / module.BACKEND_MANIFEST).read_text(encoding="utf-8"))
    settings_schema = manifest["settings_schema"]
    declared = settings_schema["properties"][module.LEVEL1_SETTING_KEY]

    jsonschema.Draft202012Validator.check_schema(settings_schema)
    jsonschema.Draft202012Validator.check_schema(declared)
    # The kit's own controller validates a written value against exactly this
    # schema, and the deployed endpoint reports its declared default.
    jsonschema.Draft202012Validator(declared).validate(sets.marker)
    assert declared["default"] == sets.marker
    # Fail-closed stays fail-closed: the manifest still refuses undeclared keys,
    # and the jobs half of the same document is untouched.
    assert settings_schema["additionalProperties"] is False
    assert manifest["jobs_schema"]["properties"] == {}


def test_the_change_set_edits_no_generated_file(applied_tree: Path, change_sets) -> None:
    """`make setup` owns the generated tree; a change set that writes it lies.

    The endpoint reads `SETTINGS_SCHEMAS` back, so a change set that wrote that
    file by hand would make the deployed probe answer without the generator ever
    having run.
    """
    _, sets = change_sets

    for path in sets.paths:
        assert GENERATED_MARKER not in (applied_tree / path).read_text(encoding="utf-8"), path
    generated = applied_tree / "services/backend/src/generated/settings_schemas.py"
    pinned = TEMPLATE_PIN.fixture_path() / "services/backend/src/generated/settings_schemas.py"
    assert generated.read_text(encoding="utf-8") == pinned.read_text(encoding="utf-8")


def test_every_spec_operation_still_names_a_declared_model(applied_tree: Path) -> None:
    """What `framework.spec.loader` resolves, checked the far side of the edit."""
    models = yaml.safe_load((applied_tree / "shared/spec/models.yaml").read_text(encoding="utf-8"))[
        "models"
    ]

    for spec_path in sorted((applied_tree / "services/backend/spec").glob("*.yaml")):
        spec = yaml.safe_load(spec_path.read_text(encoding="utf-8"))
        for name, operation in spec["operations"].items():
            for role in ("input", "output"):
                model = operation.get(role)
                assert model is None or model in models, f"{spec_path.name}:{name}:{role}"


def test_the_endpoint_lives_where_the_kit_s_own_rule_allows_a_router(change_sets) -> None:
    """`enforce_spec_compliance` allows `APIRouter()` only under `app/api/routers/`.

    The change set is the harness's stand-in for a real developer, so the route
    moved to the location the product's rule names rather than carrying a
    `# noqa` past it. The generator writes its own routers to
    `src/generated/routers/`, so this package stays the product's own.
    """
    module, _ = change_sets

    assert "routers" in Path(module.BACKEND_ENDPOINT_MODULE).parts
    assert not module.BACKEND_ENDPOINT_MODULE.startswith("services/backend/src/generated/")


def test_the_endpoint_is_mounted_and_the_command_is_wired(applied_tree: Path, change_sets) -> None:
    """The two files a `replace` had to reach, read back out of the applied tree."""
    module, sets = change_sets
    router = (applied_tree / module.BACKEND_ROUTER).read_text(encoding="utf-8")
    bot_main = (applied_tree / module.BOT_MAIN).read_text(encoding="utf-8")

    assert "from .routers.level1 import router as level1_router" in router
    assert "api_router.include_router(level1_router" in router
    # `post_init` keeps its exact contract — the kit's own unit test calls it
    # with a mock application — and `startup` is what the builder now wires.
    assert "async def post_init(application: Application) -> None:" in bot_main
    assert ".post_init(startup)" in bot_main
    assert "CommandHandler(LEVEL1_COMMAND, handle_level1)" in bot_main
    assert sets.marker in (applied_tree / module.BOT_MENU_MODULE).read_text(encoding="utf-8")


def test_the_runner_refuses_a_description_holding_two_change_sets(change_sets, runner_script):
    """One block per task description: the runner refuses to guess between two."""
    _, sets = change_sets
    doubled = sets.backend_task_description() + sets.bot_task_description()

    with pytest.raises(runner_script["MalformedChangeSet"]):
        runner_script["parse_change_set"](doubled)


def test_a_template_other_than_the_pin_is_refused(change_sets):
    """Every `replace` is an edit of the pinned render; another tree is not it."""
    module, _ = change_sets

    with pytest.raises(RuntimeError, match="pinned kit render"):
        module.build_level1_change_sets(MARKER, ("gh:vladmesh/other-kit", "9.9.9"))


# ── The extension story's change set ─────────────────────────────────────
#
# The second story of the same project edits a tree the first story already
# changed, so its own gate run starts from the applied tree rather than from the
# pristine render. Everything else is identical: the runner's own parser applies
# it, `make setup` runs the generator, and every `make lint` step the product's
# `pre-push` runs without Docker judges the result.


@pytest.fixture(scope="module")
def extension_change_set(change_sets):
    module, _ = change_sets
    return module, module.build_level1_extension_change_set(
        MARKER, EXTENSION_MARKER, (TEMPLATE_PIN.source, TEMPLATE_PIN.ref)
    )


@pytest.fixture(scope="module")
def extension_tree(tmp_path_factory, applied_tree: Path, extension_change_set, runner_script):
    """The first story's tree with the extension story's change set applied."""
    _, extension = extension_change_set
    tree = tmp_path_factory.mktemp("level1-extension") / "product"
    shutil.copytree(applied_tree, tree)
    operations = runner_script["parse_change_set"](extension.task_description())
    assert operations, "the extension task description carried no change set the runner reads"
    runner_script["apply_change_set"](operations, str(tree))
    return tree


@pytest.fixture(scope="module")
def extension_setup_tree(tmp_path_factory, extension_tree: Path) -> Path:
    """The extension tree the far side of `make setup` — what the hooks see."""
    tree = tmp_path_factory.mktemp("level1-extension-setup") / "product"
    shutil.copytree(extension_tree, tree)
    _make_setup(tree)
    return tree


def test_the_extension_tree_passes_the_kit_s_own_gate(extension_setup_tree: Path) -> None:
    """`make setup` then every `make lint` step `pre-push` runs without Docker.

    The second story's engineering turn commits in the same reused workspace and
    is held to the same product gate, so a change set the product refuses costs
    a stand run — and this one is discovered after the first story has already
    spent its forty minutes.
    """
    _assert_gate_passes(_product_gate(extension_setup_tree))


def test_the_extension_tree_is_ruff_clean_and_already_formatted(extension_tree: Path) -> None:
    """Before the generator runs, too: `make setup` lints what it was handed."""
    assert [
        (diagnostic["code"], diagnostic["filename"], diagnostic["message"])
        for diagnostic in _ruff_diagnostics(extension_tree)
    ] == []
    assert _ruff_format_check(extension_tree).returncode == 0


def test_the_generated_registry_carries_both_stories_settings(
    extension_setup_tree: Path, change_sets, extension_change_set
) -> None:
    """The real generator is asked what the second deployment will read back.

    Two declared keys, each with its own story's marker as the default the
    manifest gives it: the extension story's edit adds its key beside the first
    story's rather than over it, so a deployment that lost the first story's
    declaration fails here.
    """
    module, _ = change_sets
    registry = _load(
        "level1_extension_settings_schemas",
        extension_setup_tree / "services/backend/src/generated/settings_schemas.py",
    )

    declaring = {
        key: schema.get("default")
        for key, schema in registry.SETTINGS_SCHEMAS.items()
        if schema.get("default") in (MARKER, EXTENSION_MARKER)
    }
    assert declaring == {
        module.LEVEL1_SETTING_KEY: MARKER,
        module.LEVEL1_EXTENSION_SETTING_KEY: EXTENSION_MARKER,
    }
    assert registry.SETTINGS_SCHEMA_SOURCES[module.LEVEL1_EXTENSION_SETTING_KEY] == "backend"


def test_the_extension_endpoint_is_mounted_beside_the_first_story_s(
    extension_tree: Path, change_sets
) -> None:
    """Both routes are in the router the second story's tree carries.

    The first story's endpoint is what proves, on the deployment, that the
    branch the second story was cut from carried its merge — so a `replace` of
    the router that dropped it would make that probe meaningless.
    """
    module, _ = change_sets
    router = (extension_tree / module.BACKEND_ROUTER).read_text(encoding="utf-8")
    endpoint = (extension_tree / module.BACKEND_EXTENSION_MODULE).read_text(encoding="utf-8")

    assert "from .routers.level1 import router as level1_router" in router
    assert "from .routers.level1_extension import router as level1_extension_router" in router
    assert "api_router.include_router(level1_router" in router
    assert "api_router.include_router(level1_extension_router" in router
    assert module.LEVEL1_EXTENSION_ENDPOINT_PATH in endpoint
    # Both markers, because the deployed payload carries both: the extension
    # story's own, and the first story's beside it.
    assert EXTENSION_MARKER in endpoint
    assert MARKER in endpoint
    # And the first story's endpoint module is untouched by this change set.
    assert (extension_tree / module.BACKEND_ENDPOINT_MODULE).read_text(encoding="utf-8")


def test_the_extension_change_set_edits_no_generated_file(
    extension_tree: Path, extension_change_set
) -> None:
    """`make setup` owns the generated tree; a change set that writes it lies."""
    _, extension = extension_change_set

    for path in extension.paths:
        assert GENERATED_MARKER not in (extension_tree / path).read_text(encoding="utf-8"), path


def test_a_template_other_than_the_pin_is_refused_for_the_extension(change_sets):
    """Every `replace` is an edit of an edit of the pinned render."""
    module, _ = change_sets

    with pytest.raises(RuntimeError, match="pinned kit render"):
        module.build_level1_extension_change_set(
            MARKER, EXTENSION_MARKER, ("gh:vladmesh/other-kit", "9.9.9")
        )
