"""The level-1 change set has to survive the product's own gate, offline.

On the stand the scripted runner applies the change set, runs ``make setup`` and
commits with the product's ``.githooks`` armed — ruff, xenon, the framework's
spec validation and the product's own tests. A change set that any of those
refuse costs a stand run to find out. This module applies the same change set to
the vendored render of the pinned kit and runs, right here, everything of that
gate that can run without the product's virtualenvs:

* the *runner's own parser* — the file is executed, not reimplemented, so the
  format this suite emits is judged by the code that will read it;
* the kit's own ruff configuration, over the applied tree, the same ``ruff
  check`` and ``ruff format --check`` ``make setup`` and ``make lint`` run;
* the declarations the framework generates from: the backend manifest's
  ``settings_schema`` is checked as a JSON Schema and against the value the
  product declares for it, and every spec operation still names a declared model.

What it deliberately does not claim
-----------------------------------

``framework.generate``, ``validate_specs_cli``, ``enforce_spec_compliance`` and
``lint_controllers_cli`` live in ``codegen-kit-tooling``, a git dependency of the
*rendered product*, not of this repository. They cannot be imported here, so the
generator is not run and the generated tree is not regenerated. What is asserted
instead is that the change set hand-edits no generated file — ``make setup``
owns those — and that the declarations the generator reads stay well-formed.

The ruff binary is this repository's, not the product's pinned one. The pristine
fixture is therefore linted too, in the same test: a ruff release that starts
flagging the kit fails as a baseline, not as a defect of the change set.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
import shutil
import subprocess
import sys
from types import ModuleType

import jsonschema
import pytest
import yaml

from scripts.template_pin import TEMPLATE_PIN

REPO_ROOT = Path(__file__).resolve().parents[2]
LIVE_DIR = REPO_ROOT / "tests" / "live"
MARKER = "e2e-0f1e2d3c4b5a"
GENERATED_MARKER = "THIS FILE IS GENERATED BY THE FRAMEWORK"


def _load(name: str, path: Path) -> ModuleType:
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec and spec.loader, path
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def change_sets():
    module = _load("level1_change_set", LIVE_DIR / "level1_change_set.py")
    return module, module.build_level1_change_sets(MARKER, (TEMPLATE_PIN.source, TEMPLATE_PIN.ref))


@pytest.fixture(scope="module")
def runner_script() -> dict:
    """The scripted runner's own parser and applier, executed from its source.

    The runner ships as a ``python3 -c`` script embedded in ``noop.py``; running
    that source here is what makes this test judge the real format rather than a
    second implementation of it that can drift from it.
    """
    from worker_wrapper.runners.noop import _SCRIPT

    namespace: dict = {"__name__": "noop_runner_script"}
    exec(compile(_SCRIPT, "worker_wrapper/runners/noop.py", "exec"), namespace)  # noqa: S102
    return namespace


@pytest.fixture(scope="module")
def applied_tree(tmp_path_factory, change_sets, runner_script) -> Path:
    """The pinned kit render with both of the story's change sets applied."""
    _, sets = change_sets
    workspace = tmp_path_factory.mktemp("level1-kit")
    tree = workspace / "product"
    shutil.copytree(TEMPLATE_PIN.fixture_path(), tree)
    for description in (sets.backend_task_description(), sets.bot_task_description()):
        operations = runner_script["parse_change_set"](description)
        assert operations, "a task description carried no change set the runner recognises"
        runner_script["apply_change_set"](operations, str(tree))
    return tree


#: Exactly the exclusion `make lint` passes to `ruff format --check`.
FORMAT_EXCLUDE = "*.md,.venv/**,**/.venv/**,services/**/migrations/**"


def _ruff_format_check(tree: Path) -> subprocess.CompletedProcess:
    return _ruff(tree, "format", "--check", "--exclude", FORMAT_EXCLUDE, ".")


def _ruff(tree: Path, *args: str) -> subprocess.CompletedProcess:
    executable = shutil.which("ruff")
    assert executable, "ruff is not on PATH; run this suite through `uv run`"
    return subprocess.run(  # noqa: S603
        [executable, *args],
        cwd=tree,
        capture_output=True,
        text=True,
        check=False,
    )


def _ruff_diagnostics(tree: Path) -> list[dict]:
    result = _ruff(tree, "check", "--output-format", "json", ".")
    assert result.stdout, result.stderr
    return json.loads(result.stdout)


def test_the_pinned_kit_is_clean_before_the_change_set_touches_it() -> None:
    """The baseline, so a ruff release is never mistaken for a bad change set."""
    fixture = TEMPLATE_PIN.fixture_path()

    assert _ruff_diagnostics(fixture) == []
    assert _ruff_format_check(fixture).returncode == 0


def test_the_applied_tree_passes_the_kit_s_own_ruff(applied_tree: Path) -> None:
    """`make setup` formats and lints the whole tree; `make lint` checks it again."""
    reported = [
        (diagnostic["code"], diagnostic["filename"], diagnostic["message"])
        for diagnostic in _ruff_diagnostics(applied_tree)
    ]

    assert reported == []


def test_the_applied_tree_is_already_formatted(applied_tree: Path) -> None:
    """`pre-commit` runs `make format` and then `git add -A`.

    A change set whose files reformat is not refused by the hook — it is silently
    rewritten, and the commit then carries something other than what this suite
    wrote. That is worth failing here rather than discovering as a diff.
    """
    result = _ruff_format_check(applied_tree)

    assert result.returncode == 0, result.stdout


def test_every_change_set_file_compiles(applied_tree: Path, change_sets) -> None:
    _, sets = change_sets

    for path in sets.paths:
        if path.endswith(".py"):
            source = (applied_tree / path).read_text(encoding="utf-8")
            compile(source, path, "exec")


def test_the_product_setting_is_declared_as_a_usable_json_schema(
    applied_tree: Path, change_sets
) -> None:
    """The manifest is what the framework generates `SETTINGS_SCHEMAS` from."""
    module, sets = change_sets
    manifest = yaml.safe_load((applied_tree / module.BACKEND_MANIFEST).read_text(encoding="utf-8"))
    settings_schema = manifest["settings_schema"]
    declared = settings_schema["properties"][module.LEVEL1_SETTING_KEY]

    jsonschema.Draft202012Validator.check_schema(settings_schema)
    jsonschema.Draft202012Validator.check_schema(declared)
    # The kit's own controller validates a written value against exactly this
    # schema, and the deployed endpoint reports its declared default.
    jsonschema.Draft202012Validator(declared).validate(sets.marker)
    assert declared["default"] == sets.marker
    # Fail-closed stays fail-closed: the manifest still refuses undeclared keys,
    # and the jobs half of the same document is untouched.
    assert settings_schema["additionalProperties"] is False
    assert manifest["jobs_schema"]["properties"] == {}


def test_the_change_set_edits_no_generated_file(applied_tree: Path, change_sets) -> None:
    """`make setup` owns the generated tree; a change set that writes it lies.

    The endpoint reads `SETTINGS_SCHEMAS` back, so a change set that wrote that
    file by hand would make the deployed probe answer without the generator ever
    having run.
    """
    _, sets = change_sets

    for path in sets.paths:
        assert GENERATED_MARKER not in (applied_tree / path).read_text(encoding="utf-8"), path
    generated = applied_tree / "services/backend/src/generated/settings_schemas.py"
    pinned = TEMPLATE_PIN.fixture_path() / "services/backend/src/generated/settings_schemas.py"
    assert generated.read_text(encoding="utf-8") == pinned.read_text(encoding="utf-8")


def test_every_spec_operation_still_names_a_declared_model(applied_tree: Path) -> None:
    """What `framework.spec.loader` resolves, checked the far side of the edit."""
    models = yaml.safe_load((applied_tree / "shared/spec/models.yaml").read_text(encoding="utf-8"))[
        "models"
    ]

    for spec_path in sorted((applied_tree / "services/backend/spec").glob("*.yaml")):
        spec = yaml.safe_load(spec_path.read_text(encoding="utf-8"))
        for name, operation in spec["operations"].items():
            for role in ("input", "output"):
                model = operation.get(role)
                assert model is None or model in models, f"{spec_path.name}:{name}:{role}"


def test_the_endpoint_is_mounted_and_the_command_is_wired(applied_tree: Path, change_sets) -> None:
    """The two files a `replace` had to reach, read back out of the applied tree."""
    module, sets = change_sets
    router = (applied_tree / module.BACKEND_ROUTER).read_text(encoding="utf-8")
    bot_main = (applied_tree / module.BOT_MAIN).read_text(encoding="utf-8")

    assert "from .v1.level1 import router as level1_router" in router
    assert "api_router.include_router(level1_router" in router
    # `post_init` keeps its exact contract — the kit's own unit test calls it
    # with a mock application — and `startup` is what the builder now wires.
    assert "async def post_init(application: Application) -> None:" in bot_main
    assert ".post_init(startup)" in bot_main
    assert "CommandHandler(LEVEL1_COMMAND, handle_level1)" in bot_main
    assert sets.marker in (applied_tree / module.BOT_MENU_MODULE).read_text(encoding="utf-8")


def test_the_runner_refuses_a_description_holding_two_change_sets(change_sets, runner_script):
    """One block per task description: the runner refuses to guess between two."""
    _, sets = change_sets
    doubled = sets.backend_task_description() + sets.bot_task_description()

    with pytest.raises(runner_script["MalformedChangeSet"]):
        runner_script["parse_change_set"](doubled)


def test_a_template_other_than_the_pin_is_refused(change_sets):
    """Every `replace` is an edit of the pinned render; another tree is not it."""
    module, _ = change_sets

    with pytest.raises(RuntimeError, match="pinned kit render"):
        module.build_level1_change_sets(MARKER, ("gh:vladmesh/other-kit", "9.9.9"))
