"""Generate the runtime registry of fireable jobs from service manifests."""

from __future__ import annotations

import json
from pathlib import Path

from framework.generators.base import BaseGenerator


class JobsManifestGenerator(BaseGenerator):
    """Emit one deterministic, backend-consumable job declaration registry."""

    def generate(self) -> list[Path]:
        schemas: dict[str, object] = {}
        sources: dict[str, str] = {}
        providers: dict[str, list[str]] = {}
        for service_name, manifest in sorted(self.specs.manifests.items()):
            for name, schema in sorted(manifest.jobs_schema["properties"].items()):
                if name in schemas:
                    msg = (
                        f"Job '{name}' is declared by both '{sources[name]}' and '{service_name}'"
                    )
                    raise ValueError(msg)
                schemas[name] = schema
                sources[name] = service_name
            for capability in sorted(manifest.provides):
                providers.setdefault(capability, []).append(service_name)

        for service_dir in sorted((self.repo_root / "services").glob("*/")):
            if service_dir.name != "backend":
                continue
            output_file = service_dir / "src" / "generated" / "jobs_schemas.py"
            self.write_file(output_file, self._render_content(schemas, sources, providers))
            return [output_file]
        return []

    @staticmethod
    def _render_content(
        schemas: dict[str, object],
        sources: dict[str, str],
        providers: dict[str, list[str]],
    ) -> str:
        rendered_schemas = json.dumps(schemas, indent=4, sort_keys=True)
        rendered_sources = json.dumps(sources, indent=4, sort_keys=True)
        rendered_providers = json.dumps(providers, indent=4, sort_keys=True)
        return (
            "# AUTO-GENERATED BY SERVICE-TEMPLATE - DO NOT EDIT\n"
            '"""Fireable job declarations collected from service manifests.\n\n'
            "JOB_SCHEMAS is the fail-closed allow-list of names the core jobs contract\n"
            "may fire, mapped to the JSON Schema each fire's arguments must satisfy.\n"
            "JOB_CAPABILITY_PROVIDERS records which services declared that they provide a\n"
            "core capability. It is descriptive only: the core never resolves a provider,\n"
            'it emits the declared event and a subscriber does the work.\n"""\n\n'
            "from __future__ import annotations\n\n"
            f"JOB_SCHEMAS: dict[str, object] = {rendered_schemas}\n\n"
            f"JOB_SCHEMA_SOURCES: dict[str, str] = {rendered_sources}\n\n"
            f"JOB_CAPABILITY_PROVIDERS: dict[str, list[str]] = {rendered_providers}\n"
        )
